### PR TITLE
feat(ContributeTier): apply latest designs

### PR DESCRIPTION
**Pull request by snitin315**
Resolve https://github.com/opencollective/opencollective/issues/3888

- [x]  Goal Tier
- [x] Ticket
- [x]  Past Event
- [x] ongoing event 

# Description

Improve the information hierarchy of goal-oriented tier cards.

# Screenshots

Screenshot at 2021-02-07 08-43-48
Screenshot at 2021-02-07 08-44-06
Screenshot at 2021-02-07 08-55-37

### CODE REVIEW

**Review by Betree — COMMENTED** [review]
@snitin315 Nice change! I think the line `x individuals and y orgs...` is not there in the design, I don't think it's meant to be displayed in this view. Before moving on with this issue, I'd like to confirm this with the design team: https://github.com/opencollective/opencollective/issues/3547#issuecomment-764681391

**Review by Betree — COMMENTED** [review]
This is looking great!

The only problem that I see is with the alignment of the contribute button:
image

**Comment by snitin315** [comment]
Fixed 👍🏻 

Screenshot at 2021-02-22 18-47-55

**Review by Betree — APPROVED** [review]
Perfect! Thank you @snitin315 :raised_hands:

**Pull request merged**
