### PR TITLE
Replace tag modal with tag dropdown

### PR DESCRIPTION
**Pull request by SudharakaP**
Resolve https://github.com/opencollective/opencollective/issues/5563

https://user-images.githubusercontent.com/12435965/168883172-f1d66731-5435-4c56-b914-a43d9c4e0abd.mp4

### CODE REVIEW

**Review by Betree — COMMENTED** [review]
Can we review this with @opencollective/design (maybe tomorrow in the demo call?). The [design in Figma](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=16804%3A241197#194500320) is optimistic about the number of tags, there's no example with a scrollbar and it also doesn't have a mobile version. We should make sure that we're improving the user experience before going further.

**Comment by SudharakaP** [comment]
> Can we review this with @opencollective/design (maybe tomorrow in the demo call?). The [design in Figma](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=16804%3A241197#194500320) is optimistic about the number of tags, there's no example with a scrollbar and it also doesn't have a mobile version. We should make sure that we're improving the user experience before going further.

Sorry this missed my attention. Yes, we will review this week, but seems design has updated with a scroll bar; https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=16804%3A241197#198256688.

**Comment by SudharakaP** [comment]
> @SudharakaP I've pushed a commit to move to `StyledDropdown`, which solves the fact that this component was not accessible. I think we should have the same approach for #7854.

I've tried to support this behavior in `PopupMenu.js`; see https://github.com/opencollective/opencollective-frontend/pull/7854#issuecomment-1148000175. If you diagree with this approach, feel free to let me know and I'll change it to `StyledDropdown`. 👍🏽

**Review by Betree — APPROVED** [review]
I think this one is ready

**Comment by SudharakaP** [comment]
> I think this one is ready

Thanks. Only issue I saw was that the drop-down lacked some spacing; 

image

So I adjusted it a bit to add some margin, 

image

**Pull request merged**
