### PR TITLE
Accelerate hot reloading

### PR DESCRIPTION
**Pull request by NikitaKorevo**
Resolve ... 

# Description

- Accelerated a hot reloading
- Reduced amount of modules
- Added eslint error

# Screenshots

Example: go to http://localhost:3000/testcollective
- Hot reloading (~3s => ~1.5s)
- Amount of modules (10423 => 3119)

Before: 

before

After:

after

Eslint error:

eslint-error

### CODE REVIEW

**Review by Betree — COMMENTED** [review]
Interesting! I suppose that even if we're tree-shaking during the build, importing a large file with all icons is expensive during dev as it does so for each reload?

**Review by Betree — APPROVED** [review]
Tested locally, I can confirm the numbers:

| Step | Before | After | Change |
|------|--------|-------| -------|
/: Initial build | 7.8s | 2.5s | -68%
/: Hot reload | 1.2s | 0.5s | -58%
/: Hot reload 2 | 1.1s | 0.4s |	-63%
/babel: Initial build | 52.4s | 37.5s |	-28%
/babel: Hot reload | 3.1s | 1.8s | -42%
/babel: Hot reload 2 | 2.7s | 1.4s | -48%
/babel/expenses/9639: Initial build | 14.7s | 11.2s | -24%
/babel/expenses/9639: Hot reload | 1.8s | 1.7s | -6%
/babel/expenses/9639: Hot reload 2 | 1.8s | 1.5s | -17%

**Comment by znarf** [comment]
Looks impressive!

**Comment by Betree** [comment]
Also tried with an `npm run build` (ran 3 times for data accuracy) on my local machine, I'm going from ~450s to ~350s on average (~20% improvement). That's awesome @NikitaKorevo!

**Comment by Betree** [comment]
Merging now!

@NikitaKorevo The team has agreed to grant a $100 bounty for this one, given its impact :tada: 

To claim the bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)

**Comment by NikitaKorevo** [comment]
@Betree Thanks! Unfortunately I can't submit invoice. Wise don't work with my country (I'm from Belarus). Paypal is only available for payment. I tried to register Payoneer, but he works only with old clients from Belarus. 
Do you have other options? Maybe i can receive Yoomoney, Webmoney (WME), cryptocurrency (Tether(usdt), Bitcoin)?

**Comment by Betree** [comment]
@NikitaKorevo create the expense with the message you've posted here in the "Custom payout method info":

image

Then post the expense link here, I'll check with team members if there's something we can do.

**Comment by NikitaKorevo** [comment]
@Betree done https://opencollective.com/engineering/expenses/126304

**Pull request merged**
