### PR TITLE
HostDashboard: Enable refresh after expense status update.

### PR DESCRIPTION
**Pull request by flickz**
Resolves https://github.com/opencollective/opencollective/issues/2041

Screen Recording 2019-10-28 at 10 28 58 AM

### CODE REVIEW

**Comment by flickz** [comment]
> I'm a little sad to see how many requests are made by this page

I implemented that with sadness in my heart too 🙂 , if we do have a major redesign in the future, I believe we can have a better solution.

**Comment by znarf** [comment]
@Betree @flickz Why can't we have "Ready to pay" on the API side?

**Comment by Betree** [comment]
"Ready to pay" filter takes all the `APPROVED` expenses where:
 
> expense.collective.balance >= expense.amount

The filter was introduced in https://github.com/opencollective/opencollective-frontend/pull/1460.

What makes this query complex to implement in the API is that we need to process the balance for all the expense's Collectives to do the filtering properly.

**Comment by flickz** [comment]
@Betree For the loading state, I'm reusing existing loading implementation, I made `data.loading` to return true during `refetch`.

**Comment by Betree** [comment]
I'm afraid blocking the entire list (versus just the edited item) during loading will slow down host admins in their work. If we can't show the loading state only on the changed item easily I'd rather keep the previous version.

Peek 31-10-2019 13-25

**Comment by flickz** [comment]
I just opened a new issue to follow up the loading state https://github.com/opencollective/opencollective/issues/2583

**Pull request merged**
