### PR TITLE
Update to cypress 3.6.1

### PR DESCRIPTION
**Pull request by znarf**
Testing https://github.com/cypress-io/cypress/issues/5622#issuecomment-552027931

### CODE REVIEW

**Comment by znarf** [comment]
- in `test-e2e-0`
  - "07-signin.test.js"
     - "does not disable submit button when email has trailing spaces" is failing but the result is actually correct, it's matching the behavior in Chrome. This needs to be addressed in the codebase

**Comment by Betree** [comment]
@znarf fixed :blush:

**Comment by Betree** [comment]
Good news is that was an opportunity to fix a strange behavior on our email inputs

**Comment by znarf** [comment]
@Betree Good stuff!

**Pull request merged**
