### PR TITLE
Migrate SectionTitle.js to styled components

### PR DESCRIPTION
**Pull request by SudharakaP**
Related to https://github.com/opencollective/opencollective/issues/3289

# Screenshots

<details>
<summary>Desktop</summary>

image
</details>

<details>
<summary>Mobile</summary>

Screen Shot 2020-11-18 at 22 13 35
</details>

### CODE REVIEW

**Review by Betree — COMMENTED** [review]
Since we're only using this component in `UpdatesWithData` and `pages/orders.js`, I think we should get rid of it entirely and use the generic `H1`/`H2` components instead. `SectionTitle` is a rest from the old collective page, changed more than an year ago.

Let me know if you want me to followup on this!

**Comment by SudharakaP** [comment]
> Since we're only using this component in `UpdatesWithData` and `pages/orders.js`, I think we should get rid of it entirely and use the generic `H1`/`H2` components instead. `SectionTitle` is a rest from the old collective page, changed more than an year ago.
> 
> Let me know if you want me to followup on this!

@Betree : Are you sure it's only used in `UpdatesWithData` and `pages/order.js`? When I see it's usages I see a bunch of places such as, About.js, Contributions.js, Contributors.js, Projects.js, HostAdminCollectiveCard.js, expenses-legacy.js etc.

**Comment by Betree** [comment]
@SudharakaP Double check, but I think the ones you mention are from `components/collective-page/sections` and homepage folders. In doubt, remove the file & see where ESLint complains ;)

Also FYI, I'll be removing it from `pages/order.js` as part of the design update: https://github.com/opencollective/opencollective-frontend/pull/5424

**Comment by SudharakaP** [comment]
> @SudharakaP Double check, but I think the ones you mention are from `components/collective-page/sections` and homepage folders. In doubt, remove the file & see where ESLint complains ;)
> 
> Also FYI, I'll be removing it from `pages/order.js` as part of the design update: #5424

@Betree : Yes you are correct; it was the other component. So I've went ahead and removed SectionTitle.js and used H1 component instead for both UpdatesWithData.js and order.js. Let me know if everything looks good. 😄

**Comment by Betree** [comment]
The conflict with `pages/orders.js` is related to https://github.com/opencollective/opencollective-frontend/pull/5424, let me know if you want me to rebase to solve it.

**Comment by SudharakaP** [comment]
> The conflict with `pages/orders.js` is related to #5424, let me know if you want me to rebase to solve it.

@Betree : I've re-based it to accept changes from #5424. Everything should be okay now. 👍🏽

**Review by Betree — APPROVED** [review]

**Pull request merged**
