### PR TITLE
Add Banner for collectives with pending approval

### PR DESCRIPTION
**Pull request by flickz**
This PR follows up [#2370](https://github.com/opencollective/opencollective-api/pull/2370) to fix [#1878](https://github.com/opencollective/opencollective/issues/1878) & [#2100](https://github.com/opencollective/opencollective/issues/2100).

For `collectiveCreated` and approved.
Screenshot from 2019-08-05 19-14-08

For `collectiveCreated` and pending.
Screenshot from 2019-08-05 19-33-16

For  collective pending approval
Screenshot from 2019-08-05 19-08-50

### CODE REVIEW

**Comment by znarf** [comment]
Could you rebase?

https://github.com/opencollective/opencollective-frontend/pull/2281 should fix the e2e tests

**Comment by znarf** [comment]
Updating the copy.

**Comment by znarf** [comment]
While we're working on that:
- we should find a better color scheme than the "white text on flashy green background"
- maybe we should also add a banner for Collectives without host

**Comment by flickz** [comment]
Updated banners
Created:
Screenshot 2019-08-07 at 3 08 12 PM

Pending:
Screenshot 2019-08-07 at 3 07 08 PM

**Comment by znarf** [comment]
Updating langs

**Comment by Betree** [comment]
> Updated banners
> Created:
> Screenshot 2019-08-07 at 3 08 12 PM
> 
> Pending:
> Screenshot 2019-08-07 at 3 07 08 PM

Looks good!

**Pull request merged**
