### PR TITLE
Contribution flow: mobile stepsProgress #1727

### PR DESCRIPTION
**Pull request by leonardohof**
Resolve: opencollective/opencollective#1727

### CODE REVIEW

**Comment by leonardohof** [comment]
@Betree Could you review, please?

**Comment by leonardohof** [comment]
@Betree requested changed made. About the step name translation: I added a property for the label (labelKey). What do you think about it?

**Comment by Betree** [comment]
> About the translation of the StepName field: I added a property for the label (labelKey). What do you think about it?

Perfect! In the past react-intl complained when using a dynamic `id` in `FormattedMessage`. You had to use `defineMessages` + `int.formatMessage`. Great to see that this is now supported!

There's one last issue for me: component is not taking the full width as it should:

image

**Comment by leonardohof** [comment]
> > About the translation of the StepName field: I added a property for the label (labelKey). What do you think about it?
> 
> Perfect! In the past react-intl complained when using a dynamic `id` in `FormattedMessage`. You had to use `defineMessages` + `int.formatMessage`. Great to see that this is now supported!
> 
> There's one last issue for me: component is not taking the full width as it should:
> 
> image

Done!
image

**Pull request merged**
