### PR TITLE
Consistent Language In Team Settings

### PR DESCRIPTION
**Pull request by saideepesh000**
Resolve [opencollective/opencollective-frontend/3618](https://github.com/opencollective/opencollective/issues/3618)

# Description
Renamed Add/Remove Core Contributor to Add/Remove Team Member.

### CODE REVIEW

**Review by snitin315 — CHANGES_REQUESTED** [review]
Looks Good. Now, you can update the langs with `npm run langs:update`

**Comment by saideepesh000** [comment]
> 
> 
> Looks Good. Now, you can update the langs with `npm run langs:update`

@snitin315, I ran this command, now should I commit the changes made to the files lang/xx.json.

**Comment by snitin315** [comment]
Yes

**Comment by saideepesh000** [comment]
@snithin, @Betree, Am I suppose to anything else, please help me.

**Review by Betree — COMMENTED** [review]
It seems you generated the files from a Windows OS, which uses `\r\n` instead of `\n`. I'm not sure how you could fix your config or the `translate` script to avoid that.

@saideepesh000 let me know if you want me to fix the files & merge them.

**Comment by saideepesh000** [comment]
> 
> 
> It seems you generated the files from a Windows OS, which uses `\r\n` instead of `\n`. I'm not sure how you could fix your config or the `translate` script to avoid that.
> 
> @saideepesh000 let me know if you want me to fix the files & merge them.

@Betree, yes please help me out and sorry for this, please can you explain how to work with these lang files or any resources to follow.

**Comment by Betree** [comment]
@saideepesh000 what @snitin315 [suggested](https://github.com/opencollective/opencollective-frontend/pull/5272#pullrequestreview-515576272) is the proper way to do it. It's documented here: https://docs.opencollective.com/help/contributing/development/translations

It just seems that the `scripts/translate.js` script doesn't work great on Windows. If you have an idea on how to fix that, contributions are welcome!

**Review by snitin315 — APPROVED** [review]

**Comment by saideepesh000** [comment]
@Betree, @snitin315, thanks for helping me out, just a last one, from next time, if I want to contribute what to do.

**Pull request merged**
