### PR TITLE
refactor: refactored react-apollo implementations to @apollo

### PR DESCRIPTION
**Pull request by davejon1337**
Resolve opencollective/opencollective#2994

### CODE REVIEW

**Comment by kewitz** [comment]
@davejon1337 I think you forgot to install the packages, please make sure all tests are passing.

**Comment by davejon1337** [comment]
@kewitz `react-apollo` is already updated. can't figure out why they are failing. what else do I need to install?

**Comment by kewitz** [comment]
We need to remove `react-apollo` in favor of all the libs we're using (`@apollo/react-hooks`, etc...).

**Comment by davejon1337** [comment]
@kewitz I have installed the necessary packages. Please take a look.

**Pull request merged**
