### PR TITLE
Migrate react-tootlip -> react-popper

### PR DESCRIPTION
**Pull request by jeffin143**
Resolve part of opencollective/opencollective#2745

# Description

# Screenshots

### CODE REVIEW

**Comment by jeffin143** [comment]
@Betree , I tried migrating using https://github.com/popperjs/react-popper/blob/master/demo/index.js as refrence, Should I migrate the whole component to functional component or the current approach is find, but I am unable to trigger it on hover 
it stays as a constant 

Screenshot 2020-08-14 at 1 20 58 AM

**Comment by Betree** [comment]
@jeffin143 that's a good start! Using functional would be nice as it's the latest recommended API, but it's not a requirement for this PR. 

Two things that we still need to do:
- Let's make sure we have a clean, fresh component and remove everything legacy. For example I don't think `triggerProps` is still required if we use react-popper.
- On the behavior, the popup should stay opened when you hover it

Peek 2020-08-18 11-18

**Review by Betree — COMMENTED** [review]
Nice progress! I'm still seeing strange behaviors when moving around the cursor with the tooltip closing itself when it should not (tested on Firefox):

Peek 2020-08-24 10-37

Peek 2020-08-24 10-37-2

**Comment by jeffin143** [comment]
@Betree , Hi I know that you might have a lot of your todo list, I am really unsure why the behaviour happens, we know that react-popper only handles the positioning of popper but not the logic, Can you take a look at the logic I have used 
I am really unsure although the mouse hovers inside the div but still the popper closes 

Thanks

**Comment by Betree** [comment]
Indeed, the behavior is perfect when hovering the tooltip :ok_hand: However I'm still having some issues when hovering the icon:
Peek 2020-09-04 10-06

**Comment by Betree** [comment]
The responsiveness works great BTW :+1:

**Comment by jeffin143** [comment]
@Betree , If you have the bandwidth , can you take a pass over this pr

**Pull request merged**
