### PR TITLE
Migrate CreateEvent.js to styled components

### PR DESCRIPTION
**Pull request by SudharakaP**
Related to https://github.com/opencollective/opencollective/issues/3289

# Screenshots

image

### CODE REVIEW

**Comment by SudharakaP** [comment]
@Betree : Are we having any issues with Codecov? I don't quite understand why it's failing? 🤔

**Comment by Betree** [comment]
@SudharakaP yeah unfortunately Codecov is unstable for us lately

**Review by Betree — APPROVED** [review]
Awesome @SudharakaP, nice job!

**Comment by SudharakaP** [comment]
@Betree : You are welcome. 🙂

**Pull request merged**
