### PR TITLE
EditCollective: Add invoices section with field for invoice title

### PR DESCRIPTION
**Pull request by Betree**
Resolve https://github.com/opencollective/opencollective/issues/2390

## Edit settings

Peek 09-12-2019 17-35

## Receipt

image

### CODE REVIEW

**Comment by alanna** [comment]
Looks really good! If it's easy to do, can `payment receipt` be pre-typed in the text box, just to make it clear? If not, don't worry because it says it in the help text.

**Comment by alanna** [comment]
Also, will the example image appear on this screen? I think that will help users a lot to see what we're talking about.

**Comment by Betree** [comment]
> If it's easy to do, can payment receipt be pre-typed in the text box, just to make it clear?

It is already, it's not clear because the image size is reduced on Github:

image

> Also, will the example image appear on this screen? I think that will help users a lot to see what we're talking about.

Currently it doesn't but that's a good idea. I'll add a better screenshot now.

**Comment by Betree** [comment]
## Latest

image

**Comment by alanna** [comment]
@Betree when this change goes into production, will all existing hosts be automatically switched to "payment receipt"? Or will it only apply to new ones?

**Comment by Betree** [comment]
@alanna It's now deployed, all hosts are switched to `Payment receipt`

**Pull request merged**
