### PR TITLE
Migrate Form.js to styled components

### PR DESCRIPTION
**Pull request by SudharakaP**
Related to https://github.com/opencollective/opencollective/issues/3289

# Screenshots

Before Modification: https://imgur.com/yywXJ8C

After Modification: https://imgur.com/WFrdQdi

### CODE REVIEW

**Comment by SudharakaP** [comment]
@Betree : I've removed most of the jsx definitions as they seems not to be used. Above you can see the before and after screencasts of the whole edit collective section. While testing this I've noticed our `Goals` and `Fiscal Host` sections are not behaving well on mobile. I have opened two issues for those as well; https://github.com/opencollective/opencollective/issues/3694 and https://github.com/opencollective/opencollective/issues/3695

**Review by Betree — COMMENTED** [review]
Looking good!

I only found a mall regression on the page to edit payment methods:

### Before

Screenshot_2020-11-24 Benjamin Piouffle looooooooooooooooooooooong name - Open Collective

### After

Screenshot_2020-11-24 Benjamin Piouffle looooooooooooooooooooooong name - Open Collective(1)

**Comment by SudharakaP** [comment]
@Betree : Thanks for pointing that out. I've corrected that. Let me know if you see anything else. 👍🏽

**Comment by Betree** [comment]
Still looks a bit strange, tho my account might have pretty edge case data:

image

**Comment by SudharakaP** [comment]
@Betree : I just saw that too. Although I think it's same in staging as well. But let me correct those. 🤔

**Comment by SudharakaP** [comment]
@Betree : I've fixed it. I think we have some extraneous class names which was causing the problem. Let me know if you see any further issues. 😄

**Review by Betree — APPROVED** [review]
Looking great!

**Pull request merged**
