### PR TITLE
Allow prepaid as SourcePaymentMethod for virtualcards

### PR DESCRIPTION
**Pull request by Betree**
- Show prepaids in EditPaymentMethods

selection_910

- Show prepaids in CreateVirtualCard forms

selection_911

- Update labels icons (depending on currency) and improve label

selection_909

---

:information_source: Resolve https://github.com/opencollective/opencollective/issues/1544
:information_source: Require https://github.com/opencollective/opencollective-api/pull/1605

### CODE REVIEW

**Comment by znarf** [comment]
@Betree can we review the label for the Prepaid Payment Method? Don't think the UUID or "Transaction" make sense here. 

@xdamman what do you think?

**Comment by Betree** [comment]
@znarf sorry my screenshot is confusing, the `Transaction` shown here is actually the name I've given the the prepaid. If creating the prepaid with name="MyCompany transfer" it will show `Prepaid: MyCompany transfer`

**Comment by Betree** [comment]
@znarf Example

With name=`MyCompany wire transfer 2018-11-05`

selection_913

**Comment by xdamman** [comment]
This looks great!

**Pull request merged**
