### PR TITLE
Contributors grid: improve display order

### PR DESCRIPTION
**Pull request by Rexben001**
image

### CODE REVIEW

**Comment by znarf** [comment]
@Rexben001 Can you link to the issue it's attempting to fix in the PR description?

**Comment by Rexben001** [comment]
https://github.com/opencollective/opencollective/issues/2459

**Comment by Betree** [comment]
There are duplicate members in the screenshot you sent. That should not happen.

Also please review the original issue, the order is not right.

**Comment by Betree** [comment]
Closing in favor of https://github.com/opencollective/opencollective-frontend/pull/2749
Thank you for your contribution @Rexben001

**Pull request closed without merging**
