### PR TITLE
chore: minor code refactor

### PR DESCRIPTION
**Pull request by jamesgeorge007**
Make use of `Array.includes()` to check for presence of an element.

### CODE REVIEW

**Comment by znarf** [comment]
Tanks @jamesgeorge007 !

**Comment by Betree** [comment]
Hi @jamesgeorge007, thanks for your contribution! We have a monthly tweet to publicly thank our contributors. Would you be ok to be mentioned in it? If so, could you share your Twitter handle in it?

**Comment by jamesgeorge007** [comment]
Absolutely @Betree appreciate that :+1: 
My Twitter handle is [@james_madhacks](https://twitter.com/james_madhacks)

**Comment by jamesgeorge007** [comment]
It seems [opencollective-cli](https://github.com/opencollective/opencollective-cli) is not  actively maintained. I would love take lead if you guys were looking out for new maintainers :+1:

**Comment by znarf** [comment]
@jamesgeorge007 As of today, the `opencollective-cli ` `npm` package is effectively abandoned and we're not looking for a maintainer. There will be no update to it.

We can imagine reviving the project with new design goals and a revamped codebase. It could be published at `npm` as `@opencollective/cli` to mark the difference.

**Comment by jamesgeorge007** [comment]
@znarf I would love to give it a try. Can you gimme a better picture of how you guys see it?

**Comment by jamesgeorge007** [comment]
Am I required to create a personal repo which eventually gets published in the name `@opencollective/cli`?

**Comment by znarf** [comment]
@jamesgeorge007 I personally don't have much input at this time. Maybe you should create an issue in our main repo to try to gather feedback from the team and the community.

**Pull request merged**
