### PR TITLE
Change Remaining `/discover` links to `/search`

### PR DESCRIPTION
**Pull request by SudharakaP**
Resolve https://github.com/opencollective/opencollective/issues/5597

https://user-images.githubusercontent.com/12435965/171559206-ce766986-cc98-440a-8b78-af4baf8b0a67.mp4

### CODE REVIEW

**Comment by Betree** [comment]
> Can we have an alias and keep maintaining the /discover route ?
> 
> It's just not a good practice to 404 URLs that are existing for a long time.

@znarf https://opencollective.com/discover redirects to https://opencollective.com/search already

**Review by Betree — APPROVED** [review]

**Comment by znarf** [comment]
@Betree Where was the redirect implemented? In code here or at cloudflare?

**Review by znarf — APPROVED** [review]
No blocker for me.

**Comment by Betree** [comment]
> @Betree Where was the redirect implemented? In code here or at cloudflare?

In https://github.com/opencollective/opencollective-frontend/blob/6b3148f63e62fa926be618bb9804b14c6c6bd400/next.config.js#L198

**Comment by znarf** [comment]
@SudharakaP that was not deployed

**Comment by znarf** [comment]
@Betree thank you, too bad that doesn't work on the client side.

**Comment by SudharakaP** [comment]
> @SudharakaP that was not deployed

Ops, sorry. Seems I missed this today. I see that you've deployed it to staging; I checked each page that the url was changed and it's working correctly; so all good. Thanks.

**Pull request merged**
