### PR TITLE
hot fix for CollectiveGoals

### PR DESCRIPTION
**Pull request by znarf**
I'm not familiar with the code, just tentatively fixing a crash happening in production.

### CODE REVIEW

**Review by Betree — COMMENTED** [review]
This should have been fixed by https://github.com/opencollective/opencollective-frontend/pull/5116, do you have a link or an error message to share?

**Comment by znarf** [comment]
@Betree It's currently happening for https://opencollective.com/hrmi/edit/goals

Screenshot 2020-09-28 at 11 21 45

**Comment by znarf** [comment]
I definitely saw https://github.com/opencollective/opencollective-frontend/pull/5116 Maybe it was actually introduced by it?

**Comment by Betree** [comment]
I actually missed that some collectives were able to save their data despite the bug that was fixed in https://github.com/opencollective/opencollective-frontend/pull/5116. We have ~56 corrupted entries with an invalid `type` in the DB.

I can fix them manually, in the meantime I think the current code is working.

**Comment by Betree** [comment]
It should be fixed now, the settings for impacted collectives (including hrmi) are now properly formatted

image

**Comment by znarf** [comment]
@Betree great! so we close this PR?

**Comment by Betree** [comment]
@znarf I think we can, yes. I'll followup if there's any further issue, but we should be good now.

**Pull request closed without merging**
