### PR TITLE
fix: Issue #2180 - Event form does not let you correct errors

### PR DESCRIPTION
**Pull request by sudo-kaizen**
This pull request is aimed at fixing issue [2180](https://github.com/opencollective/opencollective/issues/2180) (Event form does not let you correct errors)

Issue statement and proposed solution has been made [here](https://github.com/opencollective/opencollective/issues/2180#issue-462348982)

Please find attached a short video of a working solution

@Betree @znarf I am very open to feedback. Thanks!

### CODE REVIEW

**Comment by sudo-kaizen** [comment]
@alanna @znarf @Betree I created a PR. Could you review please?

**Comment by sudo-kaizen** [comment]
Hello @Betree Is there any issue hindering the merge of this PR? Thanks!

**Comment by Betree** [comment]
@sudo-kaizen This one totally slipped of my view, thanks for the reminder!

**Comment by sudo-kaizen** [comment]
Awesome!

**Pull request merged**
