### PR TITLE
Updates: Display error messages

### PR DESCRIPTION
**Pull request by JohnTitor**
Fixes https://github.com/opencollective/opencollective/issues/1352

### CODE REVIEW

**Comment by JohnTitor** [comment]
I tried to display actual error message but the result is to display "Ooops, an unexpected error seems to have occurred". Any solutions?

image

**Comment by Betree** [comment]
How are you triggering the error? Did you look at the console to see if there was anything helpful in there?

**Comment by JohnTitor** [comment]
I reproduced the problem according to the procedure written in the issue. I tried to display the error message directly, but it doesn't seem to work. 

error message as shown:
```
Objects are not valid as a React child (found: Error: GraphQL error: Validation error: Validation len on title failed). If you meant to render a collection of children, use an array instead.
```

**Comment by JohnTitor** [comment]
Ah, I may solve the problem. What about this?

image

**Comment by Betree** [comment]
Looks great! Does it also works when editing an existing update?

**Comment by JohnTitor** [comment]
Oh, I forgot that. Updated.

image

**Comment by JohnTitor** [comment]
What about? @Betree

**Pull request merged**
