### PR TITLE
Added empty balance confirmation feature

### PR DESCRIPTION
**Pull request by NotJohs**
PR to feature [#2167](https://github.com/opencollective/opencollective/issues/2167)

### CODE REVIEW

**Comment by NotJohs** [comment]
please pardon my mistake with the incorrect naming of the commit message header.

**Comment by znarf** [comment]
@NotJohs just tested, works great!

However, there is 2 commits that should not be there. Can you `git rebase -i HEAD~3`, drop the 2 "twitter cards" commits then `git push --force`on your branch?

**Comment by NotJohs** [comment]
@znarf on it.

**Comment by znarf** [comment]
Great for me. @Betree do you want to have another look?

**Pull request merged**
