### PR TITLE
Hero scroll behaviour and responsiveness

### PR DESCRIPTION
**Pull request by Betree**
:deciduous_tree: See https://github.com/opencollective/opencollective/issues/1954
:art: Design: https://figma.com/file/e71tBo0Sr8J7R5n6iMkqI42d/09.-Collectives?node-id=2338%3A36062

---

There's still room for improvement and optimization for collapse animation but I wanted to propose a first version to start the conversation about it.

---

- [x] Fix Hero on scroll
- [x] Select active section
- [x] Smooth scroll on NavBar click
- [x] Hero responsiveness
- [x] Animate height transition

# Preview

- https://opencollective-frontend-ewfwnhdmun.now.sh/webpack/v2
- https://opencollective-frontend-ewfwnhdmun.now.sh/babel/v2
- https://opencollective-frontend-ewfwnhdmun.now.sh/captainfact_io/v2
- https://opencollective-frontend-ewfwnhdmun.now.sh/material-ui/v2
- https://opencollective-frontend-ewfwnhdmun.now.sh/wwcodeportland/v2

## Expend / Collapse

Peek 13-05-2019 13-31

## Section watcher

Peek 13-05-2019 13-38

### CODE REVIEW

**Comment by cuiki** [comment]
What is the URL where I can see it live? It looks good!!

**Comment by Betree** [comment]
@cuiki I forgot to add the links, it's now updated in the description:

- https://opencollective-frontend-rqgolbsfbo.now.sh/webpack/v2
- https://opencollective-frontend-rqgolbsfbo.now.sh/babel/v2
- https://opencollective-frontend-rqgolbsfbo.now.sh/captainfact_io/v2
- https://opencollective-frontend-rqgolbsfbo.now.sh/material-ui/v2
- https://opencollective-frontend-rqgolbsfbo.now.sh/wwcodeportland/v2

**Comment by Betree** [comment]
I just noticed that there is an issue with scroll when clicking on NavBar, fixing that now

**Comment by Betree** [comment]
Fixed

**Comment by Betree** [comment]
Moved `smooth-scroll` global style to `styled-components` `createGlobalStyles`.

This PR is ready to be merged.

**Pull request merged**
