### PR TITLE
fix: Text is not responsive

### PR DESCRIPTION
**Pull request by RahulBansal123**
Resolve [#3196](https://github.com/opencollective/opencollective/issues/3196)

# Description
It will fix all the css errors and will make the text easily readable in all the devices
# Screenshots

It will fix all the css errors and will make the text easily readable in all the devices
Screenshot 2020-11-19 at 1 41 11 AM

### CODE REVIEW

**Review by Betree — CHANGES_REQUESTED** [review]
Sorry for the late review! It looks way better :sparkles: 

Small issue: on the last line, the dot appears on a new line:
image

**Comment by SudharakaP** [comment]
@RahulBansal123 : Any reason why this was closed? 🤔

**Comment by RahulBansal123** [comment]
> @RahulBansal123 : Any reason why this was closed? 🤔

So, why it is not merging?

**Comment by SudharakaP** [comment]
> > @RahulBansal123 : Any reason why this was closed? thinking
> 
> So, why it is not merging?

@RahulBansal123 : I believe @Betree is still reviewing it and his last comment is not resolved yet. The changes in the `TransactionItem.js` file is not related to the linked issue as he pointed out. If you could make those changes I am sure it will eventually be merged. 😄

**Review by SudharakaP — APPROVED** [review]

**Review by Betree — APPROVED** [review]
Perfect, thank you @RahulBansal123!

**Pull request merged**
