### PR TITLE
WIP: test(e2e tests): getting rid of .click({force: true}); 

### PR DESCRIPTION
**Pull request by brymut**
Resolve: https://github.com/opencollective/opencollective/issues/2816
Retrying from: #3383 

# Description

Adress undesirable cy.get('...').click({ force: true }) usage in the cypress tests. 

# Changes

Changes made include adding a new command making use of the helper `disableSmoothScroll()`, address invisible elements due to testing viewport width/breakpoints, modifying selectors for better specificity and removing the unnecessary usages.

| Adressed  |  Occurence | Reason for use  | Change made  |   
|---|---|---|---|
| <ul><li>- [x] </li></ul>  |https://github.com/opencollective/opencollective-frontend/blob/68416b9490e95f3e2784208ee3a20610b52589ca/test/cypress/integration/04-collective_v2.test.js#L64  | Button parent not visible because of breakpoint setup  | Adjusted cypress viewport width  |
| <ul><li>- [x] </li></ul>  |https://github.com/opencollective/opencollective-frontend/blob/68416b9490e95f3e2784208ee3a20610b52589ca/test/cypress/integration/04-collective_v2.test.js#L80 |  Button parent not visible because of breakpoint setup  | Adjusted cypress viewport width  |
| <ul><li>- [x] </li></ul>  |https://github.com/opencollective/opencollective-frontend/blob/70ec8367200436b9f013fb7b9417c9f19f3b42cd/test/cypress/integration/04-organization_v2.test.js#L15  | not apparent from first implementation in #2756. Test works properly without `force: true`  | removed `force: true `without other changes |
| <ul><li>- [x] </li></ul>  |https://github.com/opencollective/opencollective-frontend/blob/68416b9490e95f3e2784208ee3a20610b52589ca/test/cypress/integration/04-organization_v2.test.js#L26  | click target is detached from DOM before .click() is executed in cypress  | changed before() hook in https://github.com/opencollective/opencollective-frontend/blob/68416b9490e95f3e2784208ee3a20610b52589ca/test/cypress/integration/04-organization_v2.test.js#L6 to beforeEach() to improve on fragility of test caused by click target being detached from DOM more likely due to re-render/ lost reference to target  |
| <ul><li>- [x] </li></ul>|https://github.com/opencollective/opencollective-frontend/blob/68416b9490e95f3e2784208ee3a20610b52589ca/test/cypress/integration/05-user_v2.test.js#L7 | not apparent from first implementation in #2756. Test works properly without `force: true`  | removed `force: true `without other changes |
| <ul><li>- [x] </li></ul>  |https://github.com/opencollective/opencollective-frontend/blob/68416b9490e95f3e2784208ee3a20610b52589ca/test/cypress/integration/05-user_v2.test.js#L30  | not apparent from first implementation in #2756. Test works properly without `force: true`  | removed `force: true `without other changes |
| <ul><li>- [x] </li></ul>  |https://github.com/opencollective/opencollective-frontend/blob/68416b9490e95f3e2784208ee3a20610b52589ca/test/cypress/integration/05-user_v2.test.js#L35 | not apparent from first implementation in #2756. Test works properly without `force: true`  | removed `force: true `without other changes |
| <ul><li>- [x] </li></ul>  | https://github.com/opencollective/opencollective-frontend/blob/68416b9490e95f3e2784208ee3a20610b52589ca/test/cypress/integration/05-user_v2.test.js#L40  | not apparent from first implementation in #2756. Test works properly without `force: true`  | removed `force: true `without other changes |
| <ul><li>- [x] </li></ul>  | https://github.com/opencollective/opencollective-frontend/blob/68416b9490e95f3e2784208ee3a20610b52589ca/test/cypress/integration/05-user_v2.test.js#L50  |  not apparent from first implementation in #2756. Test works properly without `force: true`  | removed `force: true `without other changes |
| <ul><li>- [x] </li></ul>  |  https://github.com/opencollective/opencollective-frontend/blob/68416b9490e95f3e2784208ee3a20610b52589ca/test/cypress/integration/05-user_v2.test.js#L53 | not apparent from first implementation in #2756. Test works properly without `force: true`  | removed `force: true `without other changes |
| <ul><li>- [x] </li></ul>  | https://github.com/opencollective/opencollective-frontend/blob/68416b9490e95f3e2784208ee3a20610b52589ca/test/cypress/integration/05-user_v2.test.js#L58  | not apparent from first implementation in #2756. Test works properly without `force: true`  | removed `force: true `without other changes |
| <ul><li>- [x] </li></ul>  | https://github.com/opencollective/opencollective-frontend/blob/68416b9490e95f3e2784208ee3a20610b52589ca/test/cypress/integration/06-host_v2.test.js#L14  | Click timeout issue because of a scrolling mismatch/visibility from #2691, however tests are now running fine without `force:true` | removed force:true without other changes  |
| <ul><li>- [x] </li></ul>  | https://github.com/opencollective/opencollective-frontend/blob/68416b9490e95f3e2784208ee3a20610b52589ca/test/cypress/integration/21-collective.create.test.js#L15  | not apparent from first implementation in #654, test working properly without `force: true`   | removed force:true without other changes  |
| <ul><li>- [x] </li></ul>  |  https://github.com/opencollective/opencollective-frontend/blob/68416b9490e95f3e2784208ee3a20610b52589ca/test/cypress/integration/21-collective.create.test.js#L43 | Button parent not visible because of breakpoint setup  | increased specificity of selector in `.get()` with `:visible` |
| <ul><li>- [x] </li></ul>  | https://github.com/opencollective/opencollective-frontend/blob/68416b9490e95f3e2784208ee3a20610b52589ca/test/cypress/integration/21-collective.create.test.js#L48 | Button parent not visible because of breakpoint setup  | increased specificity of selector in `.get()` with `:visible` |
| <ul><li>- [x] </li></ul>  | https://github.com/opencollective/opencollective-frontend/blob/68416b9490e95f3e2784208ee3a20610b52589ca/test/cypress/integration/21-collective.create.test.js#L50  | not apparent from first implementation in #654, test working properly without `force: true`   | removed force:true without other changes  |
| <ul><li>- [x] </li></ul>  | https://github.com/opencollective/opencollective-frontend/blob/68416b9490e95f3e2784208ee3a20610b52589ca/test/cypress/integration/22-collective.edit.test.js#L100  | element not in view because of scroll behaviour  | included `disableSmoothScroll` command in test  |
| <ul><li>- [x] </li></ul>  |  https://github.com/opencollective/opencollective-frontend/blob/593b631ab3ab3fc738fbf3d075194012e2ac1d8b/test/cypress/integration/25-host.apply.test.js#L5| Button not clickable because of multiple subjects based on scroll position  | increased specificity of selector in `.get()` with `:visible` |
| <ul><li>- [x] </li></ul>  | https://github.com/opencollective/opencollective-frontend/blob/593b631ab3ab3fc738fbf3d075194012e2ac1d8b/test/cypress/integration/26-organization.create.test.js#L10  | not apparent as first implementation during bug fix #920 may have been unnecessary, test works properly without.  | removed `force:true` without other changes   |
| <ul><li>- [x] </li></ul>  | https://github.com/opencollective/opencollective-frontend/blob/593b631ab3ab3fc738fbf3d075194012e2ac1d8b/test/cypress/integration/27-expenses.create.test.js#L15  | not apparent as first implementation during  #2005 may have been unnecessary, test works properly without.  | removed `force:true` without other changes  |
| <ul><li>- [ ] </li></ul>  | https://github.com/opencollective/opencollective-frontend/blob/593b631ab3ab3fc738fbf3d075194012e2ac1d8b/test/cypress/integration/29-host.dashboard.test.js#L8 | Button not clickable because of multiple subjects based on scroll position  | increased specificity of selector in `.get()` with `:visible`, still tracking due to detached from DOM fragility in test runs |
| <ul><li>- [x] </li></ul>  | https://github.com/opencollective/opencollective-frontend/blob/593b631ab3ab3fc738fbf3d075194012e2ac1d8b/test/cypress/integration/29-host.dashboard.test.js#L23  | not apparent from first implementation in #2977 . Test works properly without force: true | removed `force:true` without other changes  |
| <ul><li>- [x] </li></ul>  | https://github.com/opencollective/opencollective-frontend/blob/593b631ab3ab3fc738fbf3d075194012e2ac1d8b/test/cypress/integration/29-host.dashboard.test.js#L24  | not apparent from first implementation in #2977 . Test works properly without force: true | removed `force:true` without other changes  |
| <ul><li>- [x] </li></ul>  | https://github.com/opencollective/opencollective-frontend/blob/593b631ab3ab3fc738fbf3d075194012e2ac1d8b/test/cypress/integration/29-host.dashboard.test.js#L44  | not apparent from first implementation in #2977 . Test works properly without force: true | removed `force:true` without other changes  |
| <ul><li>- [x] </li></ul>  | https://github.com/opencollective/opencollective-frontend/blob/593b631ab3ab3fc738fbf3d075194012e2ac1d8b/test/cypress/integration/29-host.dashboard.test.js#L45  | not apparent from first implementation in #2977 . Test works properly without force: true | removed `force:true` without other changes  |
| <ul><li>- [x] </li></ul>  |  https://github.com/opencollective/opencollective-frontend/blob/593b631ab3ab3fc738fbf3d075194012e2ac1d8b/test/cypress/integration/29-host.dashboard.test.js#L48 | not apparent from first implementation in #2977 . Test works properly without force: true | removed `force:true` without other changes  |
| <ul><li>- [x] </li></ul>  | https://github.com/opencollective/opencollective-frontend/blob/593b631ab3ab3fc738fbf3d075194012e2ac1d8b/test/cypress/integration/29-host.dashboard.test.js#L51  | not apparent from first implementation in #2977 . Test works properly without force: true | removed `force:true` without other changes  |
| <ul><li>- [x] </li></ul>  |  https://github.com/opencollective/opencollective-frontend/blob/593b631ab3ab3fc738fbf3d075194012e2ac1d8b/test/cypress/integration/29-host.dashboard.test.js#L60 | not apparent from first implementation in #2977 . Test works properly without force: true | removed `force:true` without other changes  |
| <ul><li>- [x] </li></ul>  | https://github.com/opencollective/opencollective-frontend/blob/593b631ab3ab3fc738fbf3d075194012e2ac1d8b/test/cypress/integration/29-host.dashboard.test.js#L70  | not apparent from first implementation in #2977 . Test works properly without force: true | removed `force:true` without other changes  |
| <ul><li>- [x] </li></ul>  | https://github.com/opencollective/opencollective-frontend/blob/593b631ab3ab3fc738fbf3d075194012e2ac1d8b/test/cypress/integration/29-host.dashboard.test.js#L73  | not apparent from first implementation in #2977 . Test works properly without force: true | removed `force:true` without other changes  |
| <ul><li>- [x] </li></ul>  | https://github.com/opencollective/opencollective-frontend/blob/593b631ab3ab3fc738fbf3d075194012e2ac1d8b/test/cypress/integration/29-host.dashboard.test.js#L82  | not apparent from first implementation in #2977 . Test works properly without force: true | removed `force:true` without other changes  |
| <ul><li>- [x] </li></ul>  | https://github.com/opencollective/opencollective-frontend/blob/593b631ab3ab3fc738fbf3d075194012e2ac1d8b/test/cypress/integration/29-host.dashboard.test.js#L83  | not apparent from first implementation in #2977 . Test works properly without force: true | removed `force:true` without other changes  |

### CODE REVIEW

**Comment by znarf** [comment]
Thank you @brymut . What are the differences with the previous PR?

**Comment by brymut** [comment]
No prob @znarf, no changes to this pull request yet, still WIP but I have gone back through git to try and document all the occurrences and hopefully figure out why they were implemented so I reference back to something to work it out

**Comment by brymut** [comment]
Although, I have noticed that the test may have not been running properly with `{force: true}` included as for some reason in the cypress preview window, click the Transaction tab in the navbar doesn't work/highlight properly and doesn't scroll to the correct section.
</img>

In comparison, when I open a new tab from the test and try click through the navbar tabs, all of them work properly.

</img>

@znarf

**Comment by znarf** [comment]
Looks like it's working. Locally, I had one error with it:

Screenshot 2020-02-20 at 11 43 36

It's especially because of errors like that (detached DOM node), that I had to revert the previous PR.

I can try to merge, but the thing is that we should make sure that the suite is not only passing one time but is also reliably passing (> 90% of the time).

**Comment by brymut** [comment]
Hi again @znarf, I understand what you mean about getting the tests to pass reliably. 

> Locally, I had one error with it:

I have found it a little difficult to reproduce/spot these errors, especially the one you have just pointed out as I'm completely unable to reproduce it.

However, for the fragile test that you brought to my attention earlier from #2887  I have been able to reproduce a number of times and have been able to improve on the fragility by using beforeEach() for each section of the Organization page being tested and now I think the test is less fragile, without losing the meaning of the test objective to my understanding.

**Comment by znarf** [comment]
Merging to we can test for real!

**Comment by brymut** [comment]
More than happy to continue monitoring this as close as I can and hopefully finding better ways to address the fragile tests and document the progress & open separate issues & submit new pull requests. I feel like I'm learning a lot more on cypress using this.

**Pull request merged**
