### PR TITLE
Edit Collective settings terminology update

### PR DESCRIPTION
**Pull request by alanna**
This is just a tracking pull request. Mix got me set up using git locally. I'll let you know when it's ready for review.

### CODE REVIEW

**Comment by alanna** [comment]
Hey @znarf @Betree this is ready for review.

Here's what I did:

- Updated the terminology in the 'edit Collective' menus and pages, e.g. https://opencollective.com/testcollective/edit
- Ran `npm run build:langs`
- Got `🛑 [Error] Duplicate message id with different messages` on a couple strings and fixed that by updating all the instances of 'defaultMessage' related to that ID. Ran build:langs again and had no more errors.

I don't have a way of starting the app to check what it looks like. If you want to deploy it in staging I can have a look.

**Comment by Betree** [comment]
Hey @alanna this is perfect, we should be able to take it from there.

You can normally preview deployments with the auto-deploy on `now`:

image

**Comment by alanna** [comment]
Woohoo! My first pull request from the command line 💪

**Comment by Betree** [comment]
Well thanks for making this effort, it really makes it easier on our side :slightly_smiling_face: Merging now.

**Pull request merged**
