### PR TITLE
[enhancement]: remove markdown editor

### PR DESCRIPTION
**Pull request by maddhruv**
Completing 3 and 4 TODOs of https://github.com/opencollective/opencollective/issues/1805

#### Commits Included - 
- https://github.com/opencollective/opencollective-frontend/commit/6e23c601893c3acfdb81b0ad30330cd64011b727 - remove usage of `MarkdownEditor` from `Update Form` which is used at the collective update, instead always showing the `HTMLEditor` - with React Quill
- https://github.com/opencollective/opencollective-frontend/commit/76217cd09d8d8cf4d582fdf51acf7a253f63264e - remove usage of `MarkdownEditor` from `InputField` which is basically not used anywhere (checked for 99% coverage - where either the type is specified to markdown)
- https://github.com/opencollective/opencollective-frontend/commit/3e89bb96b6de2f58c66e380bc774ff652195365d - removes the actual `MarkdownEditor` component and file
- https://github.com/opencollective/opencollective-frontend/commit/322b167438e34fb37a93c8c5c81b6f5bd9f264b2 - uninstalls the `react-mde` dependency

### CODE REVIEW

**Comment by Betree** [comment]
I'm not sure that we reached a consensus on https://github.com/opencollective/opencollective/issues/1805 (which is why it has the `discussion` label). @znarf ?

**Comment by maddhruv** [comment]
> This issue is up to date

I thought this meant we are onto it

**Comment by znarf** [comment]
@maddhruv In March, I wrote there was no consensus and when you asked if there was any update, I said the issue was "up to date".

We'll try to discuss that internally but as of today we can't merge it.

**Comment by znarf** [comment]
Thank you for the contribution but we will be solving that a bit differently.

**Pull request closed without merging**
