### PR TITLE
Add "About" to TopBar

### PR DESCRIPTION
**Pull request by iamronen**
added an about item that links to the OC profile page team section

### CODE REVIEW

**Comment by iamronen** [comment]
I don't know.
It was (to my understanding) discussed and forgotten.

**Comment by Betree** [comment]
@iamronen This link ends up on an empty description. We have a "Company > About" link in the footer that redirects to https://docs.opencollective.com/help/about/introduction; which seems like a better fit to me.

cc @opencollective/design, this discussion is about adding an `About` link here:
image

**Comment by iamronen** [comment]
This was my first attempt to look at the codebase and attempt to make a contribution :)
I was trying to get it to go here: https://opencollective.com/opencollective#category-ABOUT

**Comment by Betree** [comment]
> This was my first attempt to look at the codebase and attempt to make a contribution :) I was trying to get it to go here: https://opencollective.com/opencollective#category-ABOUT

Yes, saw that. That's the link I'm referring to when I say `This link ends up on an empty description`. I suggest that similarly to what we do for the footer's Company > About link, we should use https://docs.opencollective.com/help/about/introduction.

image

**Pull request merged**
