### PR TITLE
Introduce mimimum amount in Tier management

### PR DESCRIPTION
**Pull request by flickz**
This PR replaces `Min(amount, presets[0])` with newly added `tier.minimumAmount`. 

Ref([#1938](https://github.com/opencollective/opencollective/issues/1938))

### CODE REVIEW

**Comment by znarf** [comment]
@flickz tests are not passing. Is it because it's requiring the API PR to be merged first? https://github.com/opencollective/opencollective-api/pull/1919

**Comment by flickz** [comment]
Yes it is

**Comment by znarf** [comment]
@flickz Something important is missing, there is no interface to create/edit the minimum amount.

**Comment by flickz** [comment]
I will add it.

**Comment by flickz** [comment]
@znarf  For Edit 
screenshot (3)

For New
screenshot (4)

**Pull request merged**
