### PR TITLE
Fix broken dev process on Windows 10

### PR DESCRIPTION
**Pull request by manuelbieh**
Tried to setup the site on my local machine with Windows 10 which didn't work quite well so I made a few small changes to get everything running on Windows.

Unfortunately I read the contribution guidelines **after** I pushed my commits. Sorry for that!

### CODE REVIEW

**Comment by znarf** [comment]
@manuelbieh Thank you. According to the first checks, that looks broken in some environments at the moment.

Also, we unfortunately don't have CircleCI running on forks, I can push your branch to our main repo to trigger that.

**Comment by manuelbieh** [comment]
Seems to be some sort of a rights problem:

> Error: spawn ./scripts/postinstall.sh EACCES

**Comment by znarf** [comment]
On MacOS, I effectively get that. `npm WARN checkPermissions Missing write access to /Users/znarf/opencollective/frontend/node_modules/jsesc` Only on your branch.

**Comment by manuelbieh** [comment]
Hmm I committed `postinstall.sh` with the wrong file permissions (644 instead of 755). This should have been the issue. The deployment is still failing but I don't see an error log anywhere.

**Comment by znarf** [comment]
Looks better!

The deploy on `now` is failing with an error. We need to fix that before merging:
https://zeit.co/opencollective/opencollective-frontend/mdawehymeh

Also, CI is passing but with a weird message at `npm ci` step. We need also to check that before merging: https://circleci.com/gh/opencollective/opencollective-frontend/4708

**Comment by znarf** [comment]
Sharing the output of `now` deploy there, because it's not public.

```
> opencollective-frontend@2.2.0 postinstall /usr/src/frontend

> cross-env ./scripts/postinstall.sh
      throw er; // Unhandled 'error' event
      ^
Error: spawn ./scripts/postinstall.sh ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

screen shot 2019-01-23 at 14 23 08

**Comment by znarf** [comment]
Stale, closing.

I hope we will revisit the issue later!

**Pull request closed without merging**
