### PR TITLE
Preserve the `/create-account` form state when moving back and forth

### PR DESCRIPTION
**Pull request by SudharakaP**
Resolve https://github.com/opencollective/opencollective/issues/5663

https://user-images.githubusercontent.com/12435965/174148836-f587bdce-74eb-4d5f-8a98-ef005a2d04a6.mp4

### CODE REVIEW

**Review by znarf — CHANGES_REQUESTED** [review]
The PR should target main.

**Comment by znarf** [comment]
Change looks good, however design is broken when I test the branch.

Screenshot 2022-06-17 at 08 56 51

**Comment by SudharakaP** [comment]
> The PR should target main.

Sorry, I thought it would be easier to base this off of the deprecation branch at first. Anyways I've created a new PR to target `main` at, https://github.com/opencollective/opencollective-frontend/pull/7916. 

> Change looks good, however design is broken when I test the branch.

This is introduced from the https://github.com/opencollective/opencollective-frontend/pull/7908 PR. I'll fix it there. Thanks for pointing it out. 👍🏽

**Comment by SudharakaP** [comment]
> This is introduced from the #7908 PR. I'll fix it there. Thanks for pointing it out. 👍🏽

I've fixed it at that PR, 

image

Commit: https://github.com/opencollective/opencollective-frontend/commit/ef23448fa8a188d5b0ee25b73cbcdc625f0b63a5

**Pull request closed without merging**
