### PR TITLE
fix(expenseitemform): enforce the amount to be set in the expense form

### PR DESCRIPTION
**Pull request by la-costa**
Resolve https://github.com/opencollective/opencollective/issues/6587

### CODE REVIEW

**Comment by Betree** [comment]
@kewitz Wdyt about this approach? I wonder if we should rather make the amount optional for drafts in the API

**Comment by kewitz** [comment]
@Betree @la-costa I agree with the original issue created. I think we should solve this from the backend by allowing drafts to:
- [ ] Not contain any expense item;
- [ ] Contain expense items with no amount set;

**Comment by Betree** [comment]
Closing as per @kewitz's [comment](https://github.com/opencollective/opencollective-frontend/pull/9488#issuecomment-1772449778) above: we want to solve this in the API.

**Comment by Betree** [comment]
And thanks for the contribution @la-costa! Sorry that the initial specs were not clearer.

**Pull request closed without merging**
