### PR TITLE
Outlook to hotmail change

### PR DESCRIPTION
**Pull request by staszewski**
Resolve #.....

# Description

I might be picky, but I was reading some of projects code thats what my eyes caught. Doesn't really provide any value. just found out that functions goal is to create hotmail but it creates outlook mail. I might be missing something 😅 
# Screenshots

### CODE REVIEW

**Review by SudharakaP — APPROVED** [review]

**Comment by staszewski** [comment]
When it will be authorized?

**Comment by SudharakaP** [comment]
@Betree : Just FYI, the E2E tests are passing on the opencollective repo branch; https://github.com/opencollective/opencollective-frontend/tree/patch-2; for some reason it doesn't pass on the fork (I did re-base the repo branch, maybe that had some impact). If no objections I'll merge this off. 😃 

@staszewski : Thanks for the contribution, we'll merge this soon. 😉

**Review by Betree — COMMENTED** [review]
Hotmail and Outlook are pretty much the same things so I don't see any reason for this change. But no blocker on my side if we can make the tests pass.

**Comment by SudharakaP** [comment]
@staszewski : Could you please rebase your fork? Just wondering why the tests pass in our [repo branch](https://github.com/opencollective/opencollective-frontend/tree/patch-2); but on in this PR. 🤔

**Comment by staszewski** [comment]
> @staszewski : Could you please rebase your fork? Just wondering why the tests pass in our [repo branch](https://github.com/opencollective/opencollective-frontend/tree/patch-2); but on in this PR. thinking

I rebased and i still cant push cause branch is up to date 🤔 How to solve it? Can't even force push

**Comment by SudharakaP** [comment]
> > @staszewski : Could you please rebase your fork? Just wondering why the tests pass in our [repo branch](https://github.com/opencollective/opencollective-frontend/tree/patch-2); but on in this PR. thinking
> 
> I rebased and i still cant push cause branch is up to date thinking How to solve it? Can't even force push

Your branch shows that it's 17 commits behind main; https://github.com/staszewski/opencollective-frontend/tree/patch-2. Did you first update your `main` branch? Try the following the following instructions on how to update the fork; https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork.

**Comment by staszewski** [comment]
> > I rebased and i still cant push cause branch is up to date thinking How to solve it? Can't even force push
> 
> @staszewski : Your branch shows that it's 17 commits behind main; https://github.com/staszewski/opencollective-frontend/tree/patch-2. Did you first update your `main` branch? Try the following the following instructions on how to update the fork; https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork.

Ok, I think I did it. Had to force cause of rebase ofc.

**Pull request merged**
