### PR TITLE
Fix styleguide compile error

### PR DESCRIPTION
**Pull request by kewitz**

### CODE REVIEW

**Review by Betree — APPROVED** [review]
@kewitz Well done. We don't get notified for these, I'm tempted to move styleguide to Vercel now that they support having multiple apps with the same repo.

**Comment by znarf** [comment]
@kewitz @Betree was that broken recently?

**Comment by kewitz** [comment]
@znarf yes. I also suspect https://oc-styleguide.onrender.com/ was also down because of this.

**Comment by kewitz** [comment]
@znarf not sure. I suspect that this was related to some folder reorganization.

**Pull request merged**
