### PR TITLE
New pricing page

### PR DESCRIPTION
**Pull request by xdamman**
- added links to /pricing from top bar and footer.
- removed link to blog from top bar to keep it short
- moved about to help and docs

### CODE REVIEW

**Comment by znarf** [comment]
@xdamman Have you noticed this PR? https://github.com/opencollective/opencollective-frontend/pull/1480

**Comment by xdamman** [comment]
Ah no I didn't notice. That would have saved me 10mn. Oh well... My bad.
Why does it have conflicts though? And why it hasn't been merged/deployed?

Anyway, the tests are passing here so should I just merge this one and close the other one? (technically this PR is a superset)

**Comment by znarf** [comment]
The other PR has conflict because other files changed in the meantime.

Last time we discussed it, the copy "We're the accountant" was a blocker. It's failing on explaining the Open Collective model.

**Comment by xdamman** [comment]
Yeah I fixed that copy. Ok merging this and closing the other one then. Thanks!

**Comment by znarf** [comment]
It seems, you didn't include the fixes to the FAQ that were in my PR: https://github.com/opencollective/opencollective-frontend/pull/1480

**Comment by xdamman** [comment]
I removed the FAQ ;-)

**Comment by znarf** [comment]
@xdamman I'm speaking about the FAQ of the pricing page.

Screen Shot 2019-03-13 at 19 07 30

**Comment by xdamman** [comment]
Ah ok, updated. Thanks.

**Pull request merged**
