### PR TITLE
Make tag search case-insensitive

### PR DESCRIPTION
**Pull request by SudharakaP**
Resolve https://github.com/opencollective/opencollective/issues/5702

https://user-images.githubusercontent.com/12435965/181372167-eadcb6b5-9146-4a0a-a542-aff685a2bdbe.mp4

### CODE REVIEW

**Review by Betree — COMMENTED** [review]
Why not do the fix on the API?

**Comment by SudharakaP** [comment]
> Why not do the fix on the API?

@Betree : We already store tags all lower-case in the db. So all we got to do is in the front-end pass the staring always as lower case. As otherwise we will have the following situation, 

image

Note that we are searching for `Meetup` and the front-end thinks this is a new tag, and passes `Meetup` to the api. We could of course lower-case this and run the search on the API side but then will still have the above problem in the front-end (showing `meetup` and `Meetup` as two tags) which we will have to fix. But when this is fixed on the front-end the requirement for any fix on the API goes away. Does that make sense? 🤔

**Comment by Betree** [comment]
> But when this is fixed on the front-end the requirement for any fix on the API goes away. Does that make sense? thinking

I don't see it like that, if a third-party consumer of the API searches for "meetup" with his homemade app/script I'm pretty sure he'll expect collectives tags with "Meetup" to be returned. Don't you think so?

**Comment by SudharakaP** [comment]
> > But when this is fixed on the front-end the requirement for any fix on the API goes away. Does that make sense? thinking
> 
> I don't see it like that, if a third-party consumer of the API searches for "meetup" with his homemade app/script I'm pretty sure he'll expect collectives tags with "Meetup" to be returned. Don't you think so?

Ah yes, you are right. I didn't think about this third-party consumer situation. I've opened an API PR to handle this; https://github.com/opencollective/opencollective-api/pull/7808. So I think we need both PRs, the front-end to make sure we don't show duplicate tags in the `/search` page and the API for the third-party consumers.

**Comment by Betree** [comment]
> So I think we need both PRs, the front-end to make sure we don't show duplicate tags in the `/search` page

I don't see how we're achieving that in this PR? It doesn't look like we're applying `uniq` on `tagStats.nodes`

**Comment by Betree** [comment]
Rebasing because matching branches are breaking the API PR

**Comment by SudharakaP** [comment]
> > So I think we need both PRs, the front-end to make sure we don't show duplicate tags in the `/search` page
> 
> I don't see how we're achieving that in this PR? It doesn't look like we're applying `uniq` on `tagStats.nodes`

What I meant here is a situation like this, 

image

where we show the duplicate `Meetup` in addition to the already existing `meetup`. So duplicate in terms of case differences. Lowercasing the tag as done here achieves that.

**Comment by Betree** [comment]
> > > So I think we need both PRs, the front-end to make sure we don't show duplicate tags in the `/search` page
> > 
> > 
> > I don't see how we're achieving that in this PR? It doesn't look like we're applying `uniq` on `tagStats.nodes`
> 
> What I meant here is a situation like this,
> 
> image
> 
> where we show the duplicate `Meetup` in addition to the already existing `meetup`. So duplicate in terms of case differences. Lowercasing the tag as done here achieves that.

I understand the issue. My comment was:
> I don't see how we're achieving that in this PR? It doesn't look like we're applying `uniq` on `tagStats.nodes`

This is what I see on https://opencollective-frontend-12au98o2n-opencollective.vercel.app/search?q=captain:
image

**Comment by SudharakaP** [comment]
> This is what I see on https://opencollective-frontend-12au98o2n-opencollective.vercel.app/search?q=captain: image

Ops, you are correct. I think I made a mistake here in assuming that the tag strings cannot have any upper case values. Anyways, I've added a commit to fix this issue by considering unique tags. Note that I've found out that we need a slight change in the API as well; https://github.com/opencollective/opencollective-api/pull/7827 so that in the above example filtering by tag `captain` returns all collectives with tags `captain` irrespective of case (such as `CAPTAIN` and `CaPTain` etc).

**Review by Betree — APPROVED** [review]

**Pull request merged**
