### PR TITLE
PreviewFeaturesModal to enable toggling preview features

### PR DESCRIPTION
**Pull request by gustavlrsn**
Consider this a proposal/pitch, was going to put together a proposal for this feature but seeing as we already had all of the API support and most frontend plumbing ready for this I figured it was not a big project to give a shot at and wouldn't hurt to have something concrete to review/consider.

There's also no external user facing parts to it unless we make the workspace a **public beta** preview feature.

# Why

Our current setup with preview/early access features where we activate them by default for certain groups on our end is causing us to be very restrictive in doing so since we do not want to disrupt anyones workflow without their choice or ability to turn it off. 

Providing easy access to toggle the preview features will allow us to include more users in testing these features, ultimately making the product better by having more early usage and feedback of features in development.

# Description

- Adding a PreviewFeaturesModal that 
  - is opened through the user profile dropdown 
    - I think this is the right place (as opposed to account settings) to make them more accessible/available on top of all parts of the platform, and is also only for users
  - only shows up if there are preview features available to the specific user
  - a preview feature can be specified to be in **public** or **closed** beta
    - if in closed beta it only shows up as an option for members of a predefined set of accounts/orgs (currently `opencollective`, `foundation`, `opensource`, `europe`) 
      - it will also show up if the user has the specific preview feature toggled on or off in the database, to be able to include anyone in a closed beta while allowing them to turn the feature on/off
- The only current preview feature, "Workspace", is configured to be in **closed beta**, so this modal will only be visible to admins of the accounts/hosts mentioned above.
- Preview features are defined in `lib/preview-features.ts`.
- The "let us know" link points to the general contact form under `/contact` but could be changed to something specific for preview feature feedback.
- The current implementation of early access features enabled the workspace by default for members of `opencollective`, this is removed since those users can now choose to enable preview features on their own.

# Screenshots
Screenshot 2023-06-14 at 20 49 55

Screenshot 2023-06-14 at 21 07 57

### CODE REVIEW

**Comment by lost-pixel-signals** [comment]
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 15  | ❗       |
    


<details>
<summary>❗ storybook/collective-page-hero--default (click to expand)</summary>

| Before | After |
| --- | --- |
|  |  |
</details>



<details>
<summary>❗ storybook/design-system-collective-navbar--customize-ct-as (click to expand)</summary>

| Before | After |
| --- | --- |
|  |  |
</details>



<details>
<summary>❗ storybook/design-system-collective-navbar--default (click to expand)</summary>

| Before | After |
| --- | --- |
|  |  |
</details>



<details>
<summary>❗ storybook/design-system-styled-collective-card--default (click to expand)</summary>

| Before | After |
| --- | --- |
|  |  |
</details>



<details>
<summary>❗ storybook/design-system-styled-collective-card--frozen-collective (click to expand)</summary>

| Before | After |
| --- | --- |
|  |  |
</details>



<details>
<summary>❗ storybook/expenses-expense-form--default (click to expand)</summary>

| Before | After |
| --- | --- |
|  |  |
</details>



<details>
<summary>❗ storybook/expenses-expense-summary--invoice (click to expand)</summary>

| Before | After |
| --- | --- |
|  |  |
</details>



<details>
<summary>❗ storybook/expenses-expense-summary--loading (click to expand)</summary>

| Before | After |
| --- | --- |
|  |  |
</details>



<details>
<summary>❗ storybook/expenses-expense-summary--receipt (click to expand)</summary>

| Before | After |
| --- | --- |
|  |  |
</details>



<details>
<summary>❗ storybook/expenses-expenses-list--default (click to expand)</summary>

| Before | After |
| --- | --- |
|  |  |
</details>



<details>
<summary>❗ storybook/expenses-expenses-list--states (click to expand)</summary>

| Before | After |
| --- | --- |
|  |  |
</details>



<details>
<summary>❗ storybook/host-dashboard-unhost-account-modal--default (click to expand)</summary>

| Before | After |
| --- | --- |
|  |  |
</details>



<details>
<summary>❗ storybook/host-dashboard-unhost-account-modal--with-balance (click to expand)</summary>

| Before | After |
| --- | --- |
|  |  |
</details>



<details>
<summary>❗ storybook/o-auth-application-approve-screen--default (click to expand)</summary>

| Before | After |
| --- | --- |
|  |  |
</details>



<details>
<summary>❗ storybook/virtual-cards-edit-virtual-card-modal--edit (click to expand)</summary>

| Before | After |
| --- | --- |
|  |  |
</details>

**Comment by Betree** [comment]
Another benefit of this: if one of the beta feature is buggy, users will be able to disable it themselves - without engineering intervention.

**Review by Betree — APPROVED** [review]
Code & feature looking great!

**Review by znarf — APPROVED** [review]
Looks good!

**Pull request merged**
