### PR TITLE
fix custom button text on tier standalone page

### PR DESCRIPTION
**Pull request by sarathsomana**
Resolve [3431](https://github.com/opencollective/opencollective/issues/3431)

### CODE REVIEW

**Review by Betree — APPROVED** [review]
Works great!

**Comment by Betree** [comment]
@sarathsomana I'm not sure why the tests are failing, it seems unrelated to your PR. Could you rebase on master to make sure?

**Comment by Betree** [comment]
@sarathsomana thank you! All green, let's ship this :rocket:

**Comment by Hmawn** [comment]
H

**Pull request merged**
