### PR TITLE
Fixed #2363 Remove deprecated style select

### PR DESCRIPTION
**Pull request by nonsodaniel**

### CODE REVIEW

**Comment by nonsodaniel** [comment]
Hi @znarf I've fixed my issue. Thanks.

**Comment by znarf** [comment]
@nonsodaniel thank you!

- can you update the PR with a better title?
- can you link to the issue? 
- have you tested that it works as expected?
- can you share a screenshot or a screen record?

**Comment by nonsodaniel** [comment]
> @nonsodaniel thank you!
> 
> * can you update the PR with a better title? Done.
> * can you link to the issue? https://github.com/opencollective/opencollective-frontend/pull/2549
> * have you tested that it works as expected?
> * can you share a screenshot or a screen record?

https://github.com/opencollective/opencollective-frontend/pull/2549

**Comment by znarf** [comment]
@nonsodaniel still 2 questions left unanswered (again)

**Comment by nonsodaniel** [comment]
> > @nonsodaniel thank you!
> > 
> > * can you update the PR with a better title? Done.
> > * can you link to the issue? #2549
> > * have you tested that it works as expected? Done.
> > * can you share a screenshot or a screen record?
> 
> #2549

style

**Comment by nonsodaniel** [comment]
style2

Deprecated style select has been removed

**Comment by Betree** [comment]
If the issue you're trying to solve is https://github.com/opencollective/opencollective/issues/2293 then please share a screenshot for the edit webhooks page - not the styleguide. As described in the issue the URL for it is `{collective_slug}/edit/webhooks`.

**Comment by znarf** [comment]
I took the time to test it, it's broken.

Before

Capture d’écran 2019-09-16 à 11 11 07

After

Capture d’écran 2019-09-16 à 11 11 40

**Comment by nonsodaniel** [comment]
I keep getting a "Not found" message whenever I get to the
http://localhost:3000/edit/webhooks  route

**Comment by znarf** [comment]
@nonsodaniel missing the collective slug in the URL ie: `http://localhost:3000/YOUR_COLLECTIVE/edit/webhooks`

**Comment by nonsodaniel** [comment]
The link to my PR:  https://github.com/opencollective/opencollective/issues/2293

newopen

**Comment by nonsodaniel** [comment]
The link to my PR:  https://github.com/opencollective/opencollective/issues/2293

newopen

**Comment by Betree** [comment]
Tested, it works now.

**Comment by nonsodaniel** [comment]
Good to know..Thanks.

**Comment by nonsodaniel** [comment]
How do I get my Bounty price?

**Pull request merged**
