### PR TITLE
TierCard: Link tier page if there's a long description

### PR DESCRIPTION
**Pull request by Betree**
image

### CODE REVIEW

**Comment by xdamman** [comment]
Can you add a “More info” link as a new line after the short description? (To be more explicit)

**Comment by Betree** [comment]
@xdamman Yes, should we still keep the link on the title?

**Comment by Betree** [comment]
Updated version

image

**Comment by xdamman** [comment]
👌 

Ship it! :-)

(Can we also link /contribute to this or is that another PR?)

**Comment by Betree** [comment]
@xdamman different scope, different PR :)

**Pull request merged**
