### PR TITLE
i18n(ja): Add translations for Japanese

### PR DESCRIPTION
**Pull request by ykzts**
A translation on UI was added. Also, fixed incorrect Japanese.

#### Broken header

screenshot on OpenCollective.org

#### Incorrect Japanese

screenshot on OpenCollective.org

### CODE REVIEW

**Comment by Betree** [comment]
Hi @yk ! :wave:

This is definitely late, but thank you for this PR!
I've rebased it and will merge it as soon as our tests pass.
I also had to remove some additional parameters to facilitate conflicts resolution.

We're currently revamping our translations system to make it more approachable, would be awesome to have you around to contribute on translations again if you want to :slightly_smiling_face:

**Comment by yk** [comment]
> Hi @yk ! 👋
> 
> This is definitely late, but thank you for this PR!
> I've rebased it and will merge it as soon as our tests pass.
> I also had to remove some additional parameters to facilitate conflicts resolution.
> 
> We're currently revamping our translations system to make it more approachable, would be awesome to have you around to contribute on translations again if you want to 🙂

I think you're mixing me up :)

**Comment by Betree** [comment]
@yk Sorry for that :worried: 

ping @ykzts :arrow_up:

**Comment by ykzts** [comment]
Oh, sorry.

In English and Japanese there are cases where word order differs, "additional parameters" is important. I will submit a PR to correct it again.

**Comment by Betree** [comment]
Awesome @ykzts, thank you. Please tag me on your pull request, I will personally make sure that we take care of it promptly this time.

**Pull request merged**
