### PR TITLE
better error message when api not reacheable on localhost

### PR DESCRIPTION
**Pull request by xdamman**

### CODE REVIEW

**Comment by znarf** [comment]
Interesting using next config to forward environment variable to the client side.

Last time we had this need, we used _document.js, maybe your approach is better.

**Comment by xdamman** [comment]
Tests fail on

```
 FAIL  src/pages/__tests__/search.test.js
  ● Test suite failed to run

    TypeError: Cannot read property 'publicRuntimeConfig' of undefined

      11 | import getConfig from 'next/config'
      12 | 
    > 13 | const { publicRuntimeConfig } = getConfig();
         |         ^
      14 | 
      15 | class ErrorPage extends React.Component {
      16 | 

      at Object.<anonymous> (src/components/ErrorPage.js:13:9)
      at Object.<anonymous> (src/pages/search.js:19:1)
      at Object.<anonymous> (src/pages/__tests__/search.test.js:8:1)
```

Any idea how to fix that? /cc @HipsterBrown

**Comment by xdamman** [comment]
@znarf yeah, this comes from their documentation. I believed at the time there wasn't any official way to do it (so it was a hack) https://github.com/zeit/next.js#exposing-configuration-to-the-server--client-side

**Comment by znarf** [comment]
@xdamman have a look at that thread https://github.com/zeit/next.js/issues/4024#issuecomment-386016077

**Comment by znarf** [comment]
screen shot 2018-08-07 at 10 25 29

Let's make sure we're not logging errors to the console while testing. We want a clean console to easily see when something is wrong.

**Comment by znarf** [comment]
PR is too old and with too many conflicts.

Feel free to revisit these ideas in a new PR if that makes sense.

**Pull request closed without merging**
