### PR TITLE
ExpenseSummary: item incurredAt display

### PR DESCRIPTION
**Pull request by Betree**
Fix https://github.com/opencollective/opencollective/issues/6452

### CODE REVIEW

**Comment by RichardLitt** [comment]
Seems like an elegant solution.

**Comment by Betree** [comment]
@RichardLitt On [this link](https://opencollective-frontend-mp2lckjan-opencollective.vercel.app/babel/expenses/9778), could you let me know what date you see here?

image

**Comment by RichardLitt** [comment]
Screenshot 2023-02-27 at 09 54 43

It flashed as 2/16, but changed the 2/15 when the page fully loaded.

**Comment by Betree** [comment]
@RichardLitt thanks for testing, how about this one https://opencollective-frontend-dr38y6vgn-opencollective.vercel.app/babel/expenses/9778 ?

**Comment by Betree** [comment]
Note that I took the opportunity to format the date differently as we know `MM-DD-YYYY` confuses people

**Comment by RichardLitt** [comment]
Screenshot 2023-02-28 at 20 26 22

Good thinking on the date format.

**Pull request merged**
