### PR TITLE
Allow collective admins to refund transactions

### PR DESCRIPTION
**Pull request by xdamman**
Fixes https://github.com/opencollective/opencollective/issues/1993

Requires https://github.com/opencollective/opencollective-api/pull/2656

### CODE REVIEW

**Comment by znarf** [comment]
Half of this PR looks like modifications to the error handling, I would prefer that to be moved in another PR so we can have a close look at it and better understand the rationale.

**Comment by xdamman** [comment]
That's why I've already separated that in two different commits in this PR to make review easier.
Given the small amount of changes and the simplicity of it, I don't think it's worth spending the extra time to create two separate PR.

**Comment by znarf** [comment]
Why would refunding fails? If I get it right, no one should ever see this error message? It's mostly a way for developers to troubleshoot?

I'm asking because if if there is chances for the admins to be in the situation, we should make sure the message is properly formatted and displayed. It's hard while reviewing to understand how it's gonna be rendered. A screenshot would have helped.

**Comment by xdamman** [comment]
(this particular  error only happens in localhost where we don't have the data of the connected stripe account)

**Pull request merged**
