### PR TITLE
Add Contact Collective Modal to Actions Button When There is No Actions Dropdown

### PR DESCRIPTION
**Pull request by SudharakaP**
Related to https://github.com/opencollective/opencollective/issues/4760

Something we have missed previously is the case when there's not actions drop-down but the user is logged in. In this case we should still show the contact modal. 

actions-dropdown-contact-modal

### CODE REVIEW

**Review by Betree — COMMENTED** [review]
We have a clear pattern on `components/collective-navbar/index.js` with buttons responsible for displaying their associated modals (`AddFundsBtn`, `ApplyToHostBtn`). Could we make it more consistent here (i.e. have a `ContactCollectiveBtn`)?

**Comment by SudharakaP** [comment]
> We have a clear pattern on `components/collective-navbar/index.js` with buttons responsible for displaying their associated modals (`AddFundsBtn`, `ApplyToHostBtn`). Could we make it more consistent here (i.e. have a `ContactCollectiveBtn`)?

Thanks. I've refactored code to include a `ContactCollectiveBtn` component. 👍🏽

**Review by Betree — COMMENTED** [review]
It would be nice to use this new components in other places where we need it, like https://github.com/opencollective/opencollective-frontend/blob/451c1a4fb9ec4c416850a16d692811d1d3faaa18/components/collective-navbar/ActionsMenu.js#L308

**Comment by SudharakaP** [comment]
> It would be nice to use this new components in other places where we need it, like
> 
> https://github.com/opencollective/opencollective-frontend/blob/451c1a4fb9ec4c416850a16d692811d1d3faaa18/components/collective-navbar/ActionsMenu.js#L308

Ops, I've missed this. I've refactored all places to use, ContactCollectiveBtn. 👍🏽

**Review by Betree — APPROVED** [review]
I haven't re-tested, so make sure all places are correctly tested before merging. Code looks good :+1:

**Pull request merged**
