### PR TITLE
Replace 'on' with 'in' in the default message collective memberOf is  0

### PR DESCRIPTION
**Pull request by maddhruv**
~`* Org seems to be hibernating on a cave in the North Pole`~
->
`* Org seems to be hibernating in a cave in the North Pole`

### CODE REVIEW

**Comment by maddhruv** [comment]
Updated the `{lang}.json` which are not `English` 'cause I thought the translation update would take time to update it from Crowdin

**Comment by znarf** [comment]
@maddhruv Usually, you should use run `npm run langs:update` and this will do whatever is needed for the translations. Maybe this is what you did? Whatever what you did, the files are properly updated, the CI job is not complaining.

@Betree do you know why the `npm run langs:update` is not updating the french translation and why the CI is not complaining?

**Comment by maddhruv** [comment]
@znarf after running `npm run langs:update` there are no updates/file changes

**Comment by Betree** [comment]
@maddhruv See the commands below for the proper way to fix it. Let me know if you want me to take care of it.
```bash
git reset --soft HEAD~0
git checkout langs/*
npm run build langs
git add langs
git commit -m "chore(NCP/Budget): Fix typo"
git push -f
```

**Comment by maddhruv** [comment]
> See the commands below for the proper way to fix it. Let me know if you want me to take care of it.

@Betree Please check this [PR](https://github.com/opencollective/opencollective-frontend/pull/2676) and last commit (changes)
If that looks fine 
I will follow up the same [steps](https://github.com/opencollective/opencollective-frontend/pull/2676#issuecomment-536917215) here as well

**Comment by maddhruv** [comment]
@znarf @Betree 
Done

**Pull request merged**
