### PR TITLE
Migrate Sponsors.js to styled components

### PR DESCRIPTION
**Pull request by SudharakaP**
Related to https://github.com/opencollective/opencollective/issues/3289

### CODE REVIEW

**Comment by SudharakaP** [comment]
@Betree : I couldn't test this one, is there any specific collective where this sponsor card appear that you know of?

**Comment by Betree** [comment]
@SudharakaP you can try https://staging.opencollective.com/captainfact_io/events/big-party-2-16658ev. It's displayed on events where you contribute to any tier that have `sponsor` in their name.

**Comment by SudharakaP** [comment]
@Betree : Thanks much. This is ready for review. 😄

**Review by Betree — APPROVED** [review]
LGTM :rocket:

**Pull request merged**
