### PR TITLE
Update name and formula of getidx() to change contributor grid

### PR DESCRIPTION
**Pull request by jeffin143**
Handling opencollective/opencollective#2459

Screenshot from 2019-10-04 14-51-05

- [x] Rename the function to getContributorIdx
- [x] Update the formula
- [x] Ensure it works with a variety of collectives, you can use
         (small) https://staging.opencollective.com/styled-icons
         (medium) https://staging.opencollective.com/vis
        (big) https://staging.opencollective.com/webpack

### CODE REVIEW

**Comment by jeffin143** [comment]
@Betree , Saw your label for squashing. Made apt changes .

Thanks :)

**Comment by Betree** [comment]
The `vis` example is not centered anymore: https://opencollective-frontend-hqpvkeniwk.now.sh/vis/v2

image

Currently it looks like this

image

A possible way to fix this would be to use the new formula (that is great!) only when `hasScroll` is true, that way we keep the display as it was for small and medium collectives (which is ok because they'll all be visible on the screen).

**Comment by Betree** [comment]
> @Betree , Saw your label for squashing. Made apt changes .

Much appreciated :slightly_smiling_face:  thanks!

**Comment by jeffin143** [comment]
> The `vis` example is not centered anymore: https://opencollective-frontend-hqpvkeniwk.now.sh/vis/v2
> 
 Ok I didn't notice that, Strangely enough previous version and the new version looked almost same, I mean had the same number of count of elements in each column. 

I have updated the PR, Could your check once now.

Also should I squash commits again?

**Comment by jeffin143** [comment]
Please have a look at the first row, The previous version had all the maintainers at the first row according to the first formula, whereas the next commit which has new formula has 2 maintainer at the top and a below, according to the new one, but then again after reverting to old formula when hasScroll is true has the same effect as previous one. 
 
Screenshot from 2019-10-04 17-02-31

Screenshot from 2019-10-04 17-02-25


But the centering is not changed, I don't know what the trouble is.

**Comment by jeffin143** [comment]
@Betree , If you are free can you take a look at this :) 

Thanks

**Comment by jeffin143** [comment]
> This looks great!

Thanks :)

**Pull request merged**
