### PR TITLE
Migrate to NextJS routes - (To Be Closed)

### PR DESCRIPTION
**Pull request by SudharakaP**
Just a draft PR to keep track of the migration. 

Related to https://github.com/opencollective/opencollective/issues/3791

### CODE REVIEW

**Comment by Betree** [comment]
@SudharakaP It's a big project, if you feel like it's going to have more complexity feel free to start by migrating just a few pages to demonstrate the change. Looks like a really good start so far, let me know if you need any help with this!

**Comment by SudharakaP** [comment]
> @SudharakaP It's a big project, if you feel like it's going to have more complexity feel free to start by migrating just a few pages to demonstrate the change. Looks like a really good start so far, let me know if you need any help with this!

Thanks a lot; will definitely let you know; but let me give it some more thought and effort. 😄  

I realize it's a bit complicated; but I like complicated stuff sometimes. 😸

**Comment by SudharakaP** [comment]
Just to give a heads up, sorry, I have been a bit busy last week, so couldn't work on this one, but I am on it and start working on it again this week. 😄

**Comment by SudharakaP** [comment]
I will close this one soon. No need to review this one; It's too messy; and I will continue this development on the new PR; https://github.com/opencollective/opencollective-frontend/pull/5855

**Comment by SudharakaP** [comment]
Closing this in favor of https://github.com/opencollective/opencollective-frontend/pull/5855

**Pull request closed without merging**
