### PR TITLE
Design System: DropdownInput && Select

### PR DESCRIPTION
**Pull request by HipsterBrown**
Implements the [design system dropdown input and select fields](https://www.figma.com/file/N4Xbl652BhzOutXmzhcrLGch/01.-Design-System-(Atoms)?node-id=32%3A192). 

Adds the following components to the Styleguide:

- `StyledDropdownInput`
- `StyledSelect`

Updates the `StyledInputGroup` with an `append` prop. 

Staging styleguide preview:
https://opencollective-styleguide.now.sh/

### CODE REVIEW

**Comment by Betree** [comment]
The behaviour is strange:
- (not important) When I click on an open select, I expect it to close itself
- When I select something then try to re-open the select it doesn't work, I need to click outside first to be able to re-open it

Made a video to show this: https://www.useloom.com/share/5c08ad39d4b7409f88bf59fb4f5aa6ba

**Comment by HipsterBrown** [comment]
@Betree Thanks for the helpful video feedback. I've fixed that behavior, so it should work as expected now.

**Comment by Betree** [comment]
@HipsterBrown That's good! Is there a way to disable the manual input? For selects without filtering we will often don't want the user to be able to put arbitrary values.

**Comment by HipsterBrown** [comment]
@Betree That would be the use case for the `StyledSelect`, I believe. The `StyledDropdownInput` would be used for filtering a list of items or allowing manual input.

**Comment by Betree** [comment]
Oh yes, perfect then :slightly_smiling_face:

**Pull request merged**
