### PR TITLE
Disable save button for events if name is empty

### PR DESCRIPTION
**Pull request by Rexben001**
Fix `Event with blank name should not be allowed #2179`

 - I checked if the name or any other input field is empty
 - If the above is true, I disable the button

---

*Edit from @Betree: https://github.com/opencollective/opencollective/issues/2179*

### CODE REVIEW

**Comment by Rexben001** [comment]
@Betree It's been fixed

**Comment by Rexben001** [comment]
@Betree @znarf

**Comment by Rexben001** [comment]
@Betree @znarf

**Comment by Betree** [comment]
I just tried and the problem's still there if title is only one space (or only contains multiple spaces).

We need to trim the value when sending it to the API **or** to trim it in the condition that you added to ensure that we don't accept empty strings.

**Comment by Rexben001** [comment]
Fixed @Betree 
I tried to trim at `event[fieldname] = value;` but the style guide was failing, so, I trimmed the name

**Pull request merged**
