### PR TITLE
enhancement: improve contribute cards layout when no activity

### PR DESCRIPTION
**Pull request by snitin315**
Resolve https://github.com/opencollective/opencollective/issues/5766

# Description

Improve contribute cards layout when no activity:

- In case of financial contributors, display a message `Be the first one to contribute!`

# Screenshots

Screenshot 2023-02-13 at 9 41 44 AM

### CODE REVIEW

**Comment by snitin315** [comment]
@Betree Friendly ping

**Comment by snitin315** [comment]
@Betree Friendly ping

**Comment by snitin315** [comment]
@Betree Friendly ping

**Review by Betree — COMMENTED** [review]
It looks like there's a conflict; we'll need to rebase.

Also, as per the issue, we want to apply this change on all contribute cards - not just "Tiers". So Events cards, Projects cards, and Tickets should also be covered.

Finally, we only want to display this message if other tiers have contributors. We don't want to end up in a situation like this one:
image

**Comment by snitin315** [comment]
@Betree Thanks for the feedback, I've updated the code to address it.

1. Collective page with financial contributions but no contributions to projects/events.

    <details>
    <summary>  screenshots    </summary>
    
    Screenshot 2023-03-05 at 8 13 08 AM
    Screenshot 2023-03-05 at 8 13 25 AM
    
    </details>

2. `/contribute` page.
    <details>
    <summary>  screenshots </summary>
    
    Screenshot 2023-03-05 at 8 19 47 AM
      
    Screenshot 2023-03-05 at 8 19 18 AM
    
    
    </details>

**Review by Betree — COMMENTED** [review]
Looking great, but it looks like the special crypto tier doesn't get the message:

image

See https://opencollective-frontend-6ftdunpiv-opencollective.vercel.app/atomex

**Comment by snitin315** [comment]
@Betree For Crypto, this is intentionally disabled, right? As described here https://github.com/opencollective/opencollective/issues/5766#issuecomment-1245134165

https://github.com/opencollective/opencollective-frontend/blob/33620e2dfee15dd2989b875bcbd810d2b5e0f1e5/components/edit-collective/sections/Tiers.js#L55

**Comment by Betree** [comment]
> @Betree For Crypto, this is intentionally disabled, right? As described here [opencollective/opencollective#5766 (comment)](https://github.com/opencollective/opencollective/issues/5766#issuecomment-1245134165)
> 
> https://github.com/opencollective/opencollective-frontend/blob/33620e2dfee15dd2989b875bcbd810d2b5e0f1e5/components/edit-collective/sections/Tiers.js#L55

Indeed! A bit sad but definitely out of scope for this PR.

**Review by Betree — APPROVED** [review]
Shipping this, thank you @snitin315!

**Pull request merged**
