### PR TITLE
Move settings button to NavBar actions

### PR DESCRIPTION
**Pull request by saideepesh000**
Resolve [opencollective/issues/3878](https://github.com/opencollective/opencollective/issues/3878)
Resolve https://github.com/opencollective/opencollective/issues/3482

# Description
This PR provides admins to view settings in their "Actions" menu on collective page Navbar

# Screenshots

Mobile View
Screenshot (19)

Desktop View
Screenshot (20)

### CODE REVIEW

**Comment by saideepesh000** [comment]
Hey, @Betree, I do not know how to write tests in general and for this PR, could you guide me in your spare time. Thanks

**Comment by snitin315** [comment]
@saideepesh000 here is the corresponding guide you may find useful - https://docs.opencollective.com/help/contributing/development/testing-with-cypress

**Comment by saideepesh000** [comment]
> 
> 
> @saideepesh000 here is the corresponding guide you may find useful - https://docs.opencollective.com/help/contributing/development/testing-with-cypress

@snitin315, thanks I'll look into this, but before that, I need to see how to write tests in cypress, and also it looks like there are some graphql and comments related tests failing, which are totally unrelated to this PR, could you please help me in finding those files, thanks.

**Comment by snitin315** [comment]
Is your branch up to date with `upstream/master`? if not try a rebase.

**Comment by saideepesh000** [comment]
> 
> 
> Is your branch up to date with `upstream/master`? if not try a rebase.

@snitin315 , Thanks, I did that, "get fetch" -> "git rebase origin/master".

**Comment by Betree** [comment]
> > @saideepesh000 here is the corresponding guide you may find useful - [docs.opencollective.com/help/contributing/development/testing-with-cypress](https://docs.opencollective.com/help/contributing/development/testing-with-cypress)
> 
> @snitin315, thanks I'll look into this, but before that, I need to see how to write tests in cypress, and also it looks like there are 

It might be a random failure, but just in case @snitin315 is right - a rebase is the way to go. It's normal if you have to force push after this, as you're re-writting the git history. Don't worry, our important branches are protected, you can't break anything :wink:

**Review by Betree — APPROVED** [review]
The code looks good to me! Nice move to add that in both `ActionsMenu` and `Navbar` :+1: 

Let's solve this issue with the tests and we'll be good to go

**Comment by saideepesh000** [comment]
> 
> 
> The code looks good to me! Nice move to add that in both `ActionsMenu` and `Navbar` 👍
> 
> Let's solve this issue with the tests and we'll be good to go

@Betree, done 👍

**Comment by Betree** [comment]
Made a few changes on the PR:
- Rebased
- Removed the legacy Settings button
- Moved the new button up the list in Navbar to make sure we display it first as it's an important call to action

**Comment by saideepesh000** [comment]
Hey @Betree @snitin315, thanks for helping me out.

**Pull request merged**
