### PR TITLE
Add Error in Crypto Flow for Less than Min Allowed Value

### PR DESCRIPTION
**Pull request by SudharakaP**
Resolve https://github.com/opencollective/opencollective/issues/4744

⚠️ Should be only merged after, https://github.com/opencollective/opencollective-frontend/pull/6941

min-amount-block

### CODE REVIEW

**Review by znarf — CHANGES_REQUESTED** [review]
There is noise in the PR, some added icons.

Also, I don't see where the `minDonation` thing is set.

**Comment by SudharakaP** [comment]
> There is noise in the PR, some added icons.
> 
> Also, I don't see where the `minDonation` thing is set.

@znarf : Just re-based from main after merging https://github.com/opencollective/opencollective-frontend/pull/6941. Now it should be good. 👍🏽

**Review by znarf — APPROVED** [review]
Good for me if it works.

**Comment by SudharakaP** [comment]
> Good for me if it works.

Thanks. Will be merging soon after the tests pass. I'll double check on staging and move to prod. 👍🏽

**Pull request merged**
