### PR TITLE
enhancement(OnBoardingModal): improve github url RegExp

### PR DESCRIPTION
**Pull request by snitin315**
Resolve https://github.com/opencollective/opencollective/issues/3507

# Description

Allow repository URL as well.

# Screenshots
Screenshot at 2020-10-15 18-25-50

### CODE REVIEW

**Review by Betree — COMMENTED** [review]
`xx/qq/zzzz` is being accepted as a valid handle, I think that should not be the case right? API seems to miss this validation as well.

**Comment by snitin315** [comment]
Hmm `xx/qq/zzzz` should not be allowed. I will see if I can tweak the RegExp more.

**Comment by Betree** [comment]
@snitin315 any news on this one?

**Comment by snitin315** [comment]
I lost track of this one. Currently, I don't have the bandwidth to work on it. I will close this PR & remove my assignment for now.

**Comment by Betree** [comment]
No problem @snitin315, thanks for starting it! I'm sure your work will be helpful for the next person who will take a look at this.

**Pull request closed without merging**
