### PR TITLE
Bad styling in the "About" description #1904

### PR DESCRIPTION
**Pull request by yellowwoods12**
No more bad styling in the "About" part of Collectives.

### CODE REVIEW

**Comment by yellowwoods12** [comment]
opencollective/opencollective #1928

**Comment by znarf** [comment]
@yellowwoods12 Thank you for contributing this. Could you share a before / after screenshots?

**Comment by yellowwoods12** [comment]
@znarf Yeah sure.
 Before :
image

After:
image

**Comment by Betree** [comment]
Preview of the fix is viewable on: https://opencollective-frontend-yzooahsvjh.now.sh/zeit

**Comment by yellowwoods12** [comment]
Your welcome :) @Betree

**Pull request merged**
