### PR TITLE
Fix - 2634 : Create gift cards form: simplify/clarify form

### PR DESCRIPTION
**Pull request by jeffin143**
Handle : https://github.com/opencollective/opencollective/issues/2634

Screenshot from 2019-11-14 23-13-20

Screenshot from 2019-11-14 23-13-26

### CODE REVIEW

**Comment by Betree** [comment]
Great!

- Can we have a +/- indicator like in the contribution flow to show the expended state:

Peek 14-11-2019 19-13

- Can we add more space below the summary and make it black/same font size tan others labels?

image

**Comment by jeffin143** [comment]
>     * Can we have a +/- indicator like in the contribution flow to show the expended state:
> 

Done :rocket: 

Screenshot from 2019-11-15 00-27-21


> 
>     * Can we add more space below the summary and make it black/same font size tan others labels?
> 
Will `18px margin-bottom` suffice ?

Screenshot from 2019-11-15 00-27-26

**Comment by Betree** [comment]
> Will 18px margin-bottom suffice ?

`32px` looks like the most consistent with existing design

**Comment by jeffin143** [comment]
>32px looks like the most consistent with existing design

Screenshot from 2019-11-18 20-56-27

**Pull request merged**
