### PR TITLE
Add delete button in more actions

### PR DESCRIPTION
**Pull request by JoyLubega**
Resolve: https://github.com/opencollective/opencollective/issues/6184

# Description
This PR moves the Delete action inside the more actions button

# Screenshots

Screenshot 2023-01-13 at 11 45 05 PM
Screenshot 2023-01-13 at 11 45 13 PM

### CODE REVIEW

**Comment by JoyLubega** [comment]
@Betree  @SudharakaP can I have a review on this?

**Review by SudharakaP — COMMENTED** [review]
We already have the modal to confirm deletion at, https://github.com/opencollective/opencollective-frontend/blob/92740eeaabb87afc5cc4cda53771a95741cef434/components/expenses/DeleteExpenseButton.js#L65-L93. I am wondering if we can reuse this instead. Maybe extract this to a separate component and use in both places.

**Comment by Betree** [comment]
Note: this is a rebase of https://github.com/opencollective/opencollective-frontend/pull/8538.

**Comment by JoyLubega** [comment]
@SudharakaP I made the changes

**Review by SudharakaP — APPROVED** [review]

**Comment by SudharakaP** [comment]
@Betree : This seems all good to me; passing it off to you in case if you have additional feedback.

**Review by Betree — APPROVED** [review]
Perfect :100:

**Pull request merged**
