### PR TITLE
Revert dependabot to previous version

### PR DESCRIPTION
**Pull request by znarf**

### CODE REVIEW

**Comment by SudharakaP** [comment]
@znarf : Unfortunately, I am not sure if this will work. I tested this on a repo of mine and just deleting the file didn't go back to previous version. 😢

**Comment by znarf** [comment]
@SudharakaP what did it do? Have you tried reinstalling the app on the repo?

**Comment by SudharakaP** [comment]
@znarf : Yes, I did reinstall the app as well. That didn't work as well; at least in my repo. After reinstalling, when I go to the dependabot-preview dashboard it says the repo is migrated to dependabot v2. But we can give it a try for sure. It says it could be disable here; https://docs.github.com/en/code-security/supply-chain-security/enabling-and-disabling-version-updates#disabling-dependabot-version-updates.

**Comment by znarf** [comment]
@SudharakaP I'm gonna do some tests on the changelog repository. Should be easier to experiment there without disprupting things.

**Comment by SudharakaP** [comment]
> @SudharakaP I'm gonna do some tests on the changelog repository. Should be easier to experiment there without disprupting things.

Surely, let me know if there's anything I could do to help; since I brought this mess in the first place. 😿

**Review by SudharakaP — APPROVED** [review]

**Pull request merged**
