### PR TITLE
Remove older host metrics section in collective settings

### PR DESCRIPTION
**Pull request by SudharakaP**
Resolve https://github.com/opencollective/opencollective/issues/4989

⚠️ Maybe we need to wait some time (a week or two) before merging this. 

@Betree : Do you think a week is appropriate? I'll put a reminder for myself on when to merge this one. 🤔

### CODE REVIEW

**Review by Betree — COMMENTED** [review]
Yep let's wait a bit before tackling that, there's no emergency

**Review by Betree — COMMENTED** [review]
We need to remove https://github.com/opencollective/opencollective-frontend/blob/ce3c490aa2e1e8f63d302a05d9d5fc6b94b96855/components/admin-panel/Menu.js#L119

**Comment by SudharakaP** [comment]
> We need to remove
> 
> https://github.com/opencollective/opencollective-frontend/blob/ce3c490aa2e1e8f63d302a05d9d5fc6b94b96855/components/admin-panel/Menu.js#L119

Sorry, I've missed this I think. I've removed that as well. 👍🏽

**Comment by Betree** [comment]
> > We need to remove
> > https://github.com/opencollective/opencollective-frontend/blob/ce3c490aa2e1e8f63d302a05d9d5fc6b94b96855/components/admin-panel/Menu.js#L119
> 
> Sorry, I've missed this I think. I've removed that as well. 👍🏽

It's not you, I think it was introduced after you opened this PR :)

**Review by Betree — APPROVED** [review]
Lgtm!

**Pull request merged**
