### PR TITLE
Show orders in settings for self-hosted accounts

### PR DESCRIPTION
**Pull request by Betree**
image

### CODE REVIEW

**Comment by Betree** [comment]
@znarf this PR implements the "Pending bank transfers" tab in the settings, all it needs to be ready is the condition to display it only for self-hosted accounts (it's currently displayed for everyone). Let me know if I can help with anything.

**Review by znarf — APPROVED** [review]
Looks good, feel free to merge when it's ready.

**Comment by znarf** [comment]
And let's turn it off for everyone for now. I will activate it in the "Self Hosting" PR.

**Comment by znarf** [comment]
I rebased.

**Comment by Betree** [comment]
@znarf I already did 10min before x)

**Comment by Betree** [comment]
Linting issue seems new, the rest should be ready to merge. Let me know if you need me to do something more here

**Pull request merged**
