### PR TITLE
Emphasize that the legal name is Optional

### PR DESCRIPTION
**Pull request by SudharakaP**
Resolve https://github.com/opencollective/opencollective/issues/4654

image

image

### CODE REVIEW

**Review by Betree — COMMENTED** [review]
The pattern we use in different places (with `StyledInputField`) is to use a dedicated intl string, which prevents us from introducing 2 version of the same string (one with "Optional, the other without).

```jsx
  <FormattedMessage
    id="OptionalFieldLabel"
    defaultMessage="{field} (optional)"
    values={{ field: labelContent }}
  />
```

- In `CreateOrganizationForm` and `CreateCollectiveMiniForm`, you can just set `required={false}` on legalName's `StyledInputField`
- In `edit-collective/Form`, we can build the label manually by adding a line in https://github.com/opencollective/opencollective-frontend/blob/ec157645e6c79047f2b7be291bfbd5439dcd0c77/components/edit-collective/Form.js#L661 like:

```es6
label: intl.formatMessage(this.messages.optional, { field: intl.formatMessage(this.messages.legalNameBaseLabel) })
```

**Comment by SudharakaP** [comment]
> The pattern we use in different places (with `StyledInputField`) is to use a dedicated intl string, which prevents us from introducing 2 version of the same string (one with "Optional, the other without).
> 
> ```js
>   <FormattedMessage
>     id="OptionalFieldLabel"
>     defaultMessage="{field} (optional)"
>     values={{ field: labelContent }}
>   />
> ```
> 
>     * In `CreateOrganizationForm` and `CreateCollectiveMiniForm`, you can just set `required={false}` on legalName's `StyledInputField`
> 
>     * In `edit-collective/Form`, we can build the label manually by adding a line in https://github.com/opencollective/opencollective-frontend/blob/ec157645e6c79047f2b7be291bfbd5439dcd0c77/components/edit-collective/Form.js#L661
>        like:
> 
> 
> ```js
> label: intl.formatMessage(this.messages.optional, { field: intl.formatMessage(this.messages.legalNameBaseLabel) })
> ```

Thanks for the feedback. I've changed the code according to this. 👍🏽

**Review by Betree — APPROVED** [review]
Looks good, thanks for iterating :sparkles:

**Comment by SudharakaP** [comment]
> Looks good, thanks for iterating sparkles

You are welcome. 😄

**Pull request merged**
