### PR TITLE
Expense block design changes

### PR DESCRIPTION
**Pull request by hdiniz**
Related https://github.com/opencollective/opencollective/issues/6675

# Description

https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP?type=design&node-id=20530:95717

# Screenshots

Desktop
image

Mobile
image

### CODE REVIEW

**Comment by lost-pixel-signals** [comment]
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 2       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 4  | ❗       |
    


*🟡 storybook/expenses-expense-budget-item--default*: 


| Image |
| --- |
|  |



*🟡 storybook/expenses-expense-budget-item--multi-currency*: 


| Image |
| --- |
|  |



*❗ storybook/collective-page-hero--default*: 


| Before | After |
| --- | --- |
|  |  |



*❗ storybook/design-system-loading-grid--default*: 


| Before | After |
| --- | --- |
|  |  |



*❗ storybook/expenses-expenses-list--default*: 


| Before | After |
| --- | --- |
|  |  |



*❗ storybook/expenses-expenses-list--states*: 


| Before | After |
| --- | --- |
|  |  |

**Comment by lost-pixel-signals** [comment]
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 2       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 2  | ❗       |
    


*🟡 storybook/expenses-expense-budget-item--default*: 


| Image |
| --- |
|  |



*🟡 storybook/expenses-expense-budget-item--multi-currency*: 


| Image |
| --- |
|  |



*❗ storybook/expenses-expenses-list--default*: 


| Before | After |
| --- | --- |
|  |  |



*❗ storybook/expenses-expenses-list--states*: 


| Before | After |
| --- | --- |
|  |  |

**Comment by lost-pixel-signals** [comment]
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 5  | ❗       |
    


*❗ storybook/collective-page-hero--default*: 


| Before | After |
| --- | --- |
|  |  |



*❗ storybook/design-system-loading-grid--default*: 


| Before | After |
| --- | --- |
|  |  |



*❗ storybook/design-system-loading-grid--loading-grid-colors*: 


| Before | After |
| --- | --- |
|  |  |



*❗ storybook/design-system-loading-grid--loading-grid-sizes*: 


| Before | After |
| --- | --- |
|  |  |



*❗ storybook/o-auth-application-approve-screen--auto-approve-redirecting*: 


| Before | After |
| --- | --- |
|  |  |

**Comment by lost-pixel-signals** [comment]
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 4  | ❗       |
    


*❗ storybook/design-system-loading-grid--default*: 


| Before | After |
| --- | --- |
|  |  |



*❗ storybook/design-system-loading-grid--loading-grid-colors*: 


| Before | After |
| --- | --- |
|  |  |



*❗ storybook/design-system-loading-grid--loading-grid-sizes*: 


| Before | After |
| --- | --- |
|  |  |



*❗ storybook/o-auth-application-approve-screen--auto-approve-redirecting*: 


| Before | After |
| --- | --- |
|  |  |

**Comment by lost-pixel-signals** [comment]
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 7  | ❗       |
    


<details>
<summary>❗ storybook/collective-page-hero--default (click to expand)</summary>

| Before | After |
| --- | --- |
|  |  |
</details>



<details>
<summary>❗ storybook/design-system-collective-navbar--customize-ct-as (click to expand)</summary>

| Before | After |
| --- | --- |
|  |  |
</details>



<details>
<summary>❗ storybook/design-system-loading-grid--default (click to expand)</summary>

| Before | After |
| --- | --- |
|  |  |
</details>



<details>
<summary>❗ storybook/design-system-loading-grid--loading-grid-colors (click to expand)</summary>

| Before | After |
| --- | --- |
|  |  |
</details>



<details>
<summary>❗ storybook/design-system-loading-grid--loading-grid-sizes (click to expand)</summary>

| Before | After |
| --- | --- |
|  |  |
</details>



<details>
<summary>❗ storybook/expenses-expenses-list--states (click to expand)</summary>

| Before | After |
| --- | --- |
|  |  |
</details>



<details>
<summary>❗ storybook/o-auth-application-approve-screen--auto-approve-redirecting (click to expand)</summary>

| Before | After |
| --- | --- |
|  |  |
</details>

**Review by gustavlrsn — COMMENTED** [review]
The new component takes up considerable vertical space
Screenshot 2023-06-15 at 11 32 27

If we reduce the size of the buttons a bit and tuck them up a higher into the component I think we're good:
image

Also needs some space between the security checks indicator and the other buttons.

**Comment by gustavlrsn** [comment]
A bit late perhaps, but also noticing when testing this that the attachments indicator seemed more natural styled as a button as opposed to a link since it opens a modal and not links to another page:
image

ping @opencollective/design

**Comment by Memo-Es** [comment]
@gustavlrsn, these items should be the same as we are using for the new activity feed:

Screen Shot on 2023-06-15 at 21-17-03

So, yes, I agree with that update. Thank you!

**Comment by lost-pixel-signals** [comment]
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 4  | ❗       |
    


*❗ storybook/expenses-expense-budget-item--default*: 


| Before | After |
| --- | --- |
|  |  |



*❗ storybook/expenses-expense-budget-item--multi-currency*: 


| Before | After |
| --- | --- |
|  |  |



*❗ storybook/expenses-expenses-list--default*: 


| Before | After |
| --- | --- |
|  |  |



*❗ storybook/expenses-expenses-list--states*: 


| Before | After |
| --- | --- |
|  |  |

**Comment by lost-pixel-signals** [comment]
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 4  | ❗       |
    


*❗ storybook/expenses-expense-budget-item--default*: 


| Before | After |
| --- | --- |
|  |  |



*❗ storybook/expenses-expense-budget-item--multi-currency*: 


| Before | After |
| --- | --- |
|  |  |



*❗ storybook/expenses-expenses-list--default*: 


| Before | After |
| --- | --- |
|  |  |



*❗ storybook/expenses-expenses-list--states*: 


| Before | After |
| --- | --- |
|  |  |

**Comment by Betree** [comment]
We're adding agreements in the expense block with https://github.com/opencollective/opencollective-frontend/pull/9038, let's make sure it gets included in the redesign as well :slightly_smiling_face:

**Pull request closed without merging**
