### PR TITLE
PublishUpdateBtnWithData: remove styled-jsx in favor of styled-components

### PR DESCRIPTION
**Pull request by snitin315**
Refers https://github.com/opencollective/opencollective/issues/3289

# Description

# Screenshots

Screenshot at 2020-08-23 10-51-48

### CODE REVIEW

**Review by Betree — APPROVED** [review]
All good, nice work @snitin315 :+1:

**Comment by Betree** [comment]
Two tests are failing after this change:

```
   1) create an update
       edit info:
     AssertionError: Timed out retrying: Expected to find element: `.UpdatePage .PublishUpdateBtn`, but never found it.
      at Context.eval (http://localhost:3000/__cypress/tests?p=test/cypress/integration/28-update.create.test.js:17:12)

  2) random user cannot see update
       cannot view private update:
     AssertionError: Timed out retrying: Expected to find element: `[data-cy=updateTitle]`, but never found it.
      at Context.eval (http://localhost:3000/__cypress/tests?p=test/cypress/integration/28-update.create.test.js:31:12)
```

We need to target these elements through their `data-cy` prop (`cy.get('[data-cy=PublishUpdateBtn]')`)

**Comment by snitin315** [comment]
@Betree Thanks for pointing. I have fixed the tests.

**Comment by Betree** [comment]
Fantastic, thank you @snitin315!

**Pull request merged**
