### PR TITLE
design for webhook administration

### PR DESCRIPTION
**Pull request by NotJohs**
re [#2049](https://github.com/opencollective/opencollective/issues/2049)

### CODE REVIEW

**Comment by znarf** [comment]
@NotJohs to fix the "update-langs" test, just run `npm run build:langs` and commit the result

**Comment by NotJohs** [comment]
@znarf Thanks. Done

**Comment by znarf** [comment]
@NotJohs the commit history is not right :-/ looks like a failed rebase. can you find a way to fix that?

**Comment by NotJohs** [comment]
@znarf I am a little bit stumped, please could you give me a bit more information.

**Comment by znarf** [comment]
@NotJohs we're not supposed to commits that are not related to your branch here

Capture d’écran 2019-07-08 à 15 04 32

**Comment by NotJohs** [comment]
@znarf That happened after I merged with upstream to synchronize my fork.
Pardon me, I don't have much experience using git.

**Comment by znarf** [comment]
@NotJohs I'll try to solve it for you then.

**Comment by znarf** [comment]
@NotJohs I edited your PR here https://github.com/opencollective/opencollective-frontend/pull/2106

Some Git tricks:

- make sure to always start from a fresh `master` when working on a new feature
 - `git checkout master`
 - `git pull --rebase origin master`
 - `git checkout -b feat/myfeature`
- if the PR can't be merged, rebase master
 - `git pull --rebase origin master`
 - `git push origin` and only when needed `git push origin --force`
- if the commit history is not clean, rebase interactive
 - `git rebase -i HEAD~6`

**Comment by NotJohs** [comment]
@znarf thanks, I really learned a lot.

**Pull request closed without merging**
