### PR TITLE
Granular freeze

### PR DESCRIPTION
**Pull request by macovedj**
Initial attempt at [this](https://github.com/opencollective/opencollective/issues/5383#issuecomment-1116951033)

### CODE REVIEW

**Review by Betree — CHANGES_REQUESTED** [review]
@macovedj This is not the right solution for this problem, we want to implement this in the API to make sure frozen accounts will be blocked everywhere - regardless of the application they're using.

**Comment by Betree** [comment]
My bad, I misunderstood the code and didn't realize you also made an API implementation.

There's still some unnecessary complexity in this PR. For example, I don't think we want to change the prototype for `hasAccessToFeature`. It's the API responsibility to return the right value for the feature when it's disabled.

**Comment by macovedj** [comment]
A bit busy this week.  But I'd like to get around to thinking about taking your notes into account sometime soon @Betree

**Comment by Betree** [comment]
Closing as stale. We made some progres on this topic after https://github.com/opencollective/opencollective/issues/3593

**Pull request closed without merging**
