### PR TITLE
translations - first half

### PR DESCRIPTION
**Pull request by piamancini**

### CODE REVIEW

**Comment by eatskolnikov** [comment]
Found it! I'll help you out on this one

**Comment by piamancini** [comment]
@eatskolnikov you are a hero!

**Comment by eatskolnikov** [comment]
@piamancini I thought you made the PR from a fork and my first idea was to add my changes on your PR so we would only have 1 PR and have things neat and clean. But because the branch is from the main repo I can't do that. So, I had to create a new PR #490 your commits are included there. Sorry for the inconvenience :(

**Comment by Betree** [comment]
Closing this in favor of https://github.com/opencollective/opencollective-frontend/pull/490 that contains all the changes from Pia

**Pull request closed without merging**
