### PR TITLE
Add submit expense page

### PR DESCRIPTION
**Pull request by hdiniz**
Related https://github.com/opencollective/opencollective/issues/7606
Require https://github.com/opencollective/opencollective-api/pull/10447

### CODE REVIEW

**Review by gustavlrsn — COMMENTED** [review]
Having some issues when trying to submit, the expense items section fails the validation and is marked as required, but unclear what is missing:

image

**Comment by gustavlrsn** [comment]
Might only be my development environment, but getting this "problem refreshing the Wise token" when trying to submit also:

image

**Comment by gustavlrsn** [comment]
Validation hint missing when not having selected the type of expense:

image

**Comment by hdiniz** [comment]
I have made the default expense type selection to invoice and fixed the validation hint on the expense item attachment.

For testing locally, try submitting with a payment method of type Other as that does not require any integrations.

**Pull request merged**
