### PR TITLE
fix: Date Time Format

### PR DESCRIPTION
**Pull request by RahulBansal123**
Resolve [#3646](https://github.com/opencollective/opencollective/issues/3646)

# Description

Fixed the date time format.

### CODE REVIEW

**Review by kewitz — APPROVED** [review]
Perfect, thank you!

**Comment by kewitz** [comment]
@Betree, could you please add @RahulBansal123 to the contributors' team?

**Comment by Betree** [comment]
Done :heavy_check_mark:

**Comment by znarf** [comment]
@kewitz This is breaking E2E, I'll have to revert.

**Pull request merged**
