### PR TITLE
TailwindCSS

### PR DESCRIPTION
**Pull request by gustavlrsn**
### Description
- adding TailwindCSS as per [the RFC to adopt it](https://github.com/opencollective/opencollective/pull/6694)
- removing some global styles that are either unused, being set by Tailwind's style reset, or conflict with Tailwind
  - removed global font-size, and adjusted all rem values using a script to work with the default base font size of 16px
- Fixed the styling of static pages that expected some global styles to work, added new markdown classes based on tailwind to `app.css`
- Making sure CollectiveThemeProvider works with extended tailwind color `primary`

### CODE REVIEW

**Review by Betree — COMMENTED** [review]
No blocker for me so far on the code; I like how this also removes legacy global CSS debt.

Below are some visual regressions I noticed :arrow_down: 

## Updates page

No max-width on content
https://opencollective-frontend-rcrahvo8x-opencollective.vercel.app/captainfact_io/updates

image


## Expense form

Font sizes got bigger
https://opencollective-frontend-rcrahvo8x-opencollective.vercel.app/captainfact_io/expenses/new

<table>
<tr>
 <td>Before
 <td>After
<tr>
 <td>

image

 <td>

image

</table>

**Comment by gustavlrsn** [comment]
@Beetree thank you for the review, I fixed the two styling regressions you found + another one

**Comment by gustavlrsn** [comment]
A bunch more visual regressions found with Lost Pixel (what a great tool!): https://app.lost-pixel.com/app/repos/cli4di7pd2hrtmo0erdfumlpp/cli4e0w6q2kjzmo0el8bu56i1?build=clldrbgeh49fgna0emf5uccin

Still need to go through these.

**Comment by gustavlrsn** [comment]
> A bunch more visual regressions found with Lost Pixel (what a great tool!): https://app.lost-pixel.com/app/repos/cli4di7pd2hrtmo0erdfumlpp/cli4e0w6q2kjzmo0el8bu56i1?build=clldrbgeh49fgna0emf5uccin
> 
> Still need to go through these.

These are fixed.

**Pull request merged**
