### PR TITLE
Add pre-deploy script

### PR DESCRIPTION
**Pull request by Betree**
This script runs before starting the deploy.
1. It shows a log of all the commits about to be pushed
2. It ask for a confirmation (y/n)
3. If a slack user token is set, it notifies slack `#engineering` channel with the `git log` attached

It looks like that:
```bash
$ npm run deploy:staging
----------------
commit 61bc9255668f44c1532dcf28421a99b3b9f036a4 (origin/master, origin/HEAD)
Merge: 025b4eff fd36f8af
Author: François Hodierne <francois@hodierne.net>
Date:   Mon Nov 12 14:54:13 2018 +0100

    Merge pull request #1032 from opencollective/fix/906-large-images-error-message

    Show error message when file size exceed limit

commit 025b4eff3cb18e64481820d49d06df394c64e589
Merge: 256e4e0c da011f5f
Author: François Hodierne <francois@hodierne.net>
Date:   Mon Nov 12 14:53:59 2018 +0100

    Merge pull request #1033 from opencollective/feature/ip-forwarding

    Process IP address and forward to proxy

commit da011f5fde6e0c3f03ffb172cd0a32030d608e72 (origin/feature/ip-forwarding)
Author: François Hodierne <francois@hodierne.net>
Date:   Mon Nov 12 12:50:33 2018 +0100

    build: update cloudflare IPs on build
----------------
ℹ️  You're about to deploy the preceding commits from master branch to staging server.
❔ Are you sure (yes/no) > y
🔔  Slack notified about this deployment.
🚀  Deploying now...
```

---

**In slack**
Slack preview

### How to configure Slack token

1. Go to https://api.slack.com/custom-integrations/legacy-tokens
2. Generate a token for the OpenCollective workspace
3. Put your token in your `~/.bashrc` or `~/.zshrc` (depending on your shell) and restart your shell

```bash
export OC_SLACK_USER_TOKEN=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

### CODE REVIEW

**Comment by HipsterBrown** [comment]
@Betree Can we add documentation about this somewhere? Possibly under the "Deployment" section of the README. It looks like a great feature. :+1:

**Comment by Betree** [comment]
@HipsterBrown Nice catch, I've added the instructions to `README.md`

**Comment by Betree** [comment]
@znarf Script + README updated to load Slack token from `.env`

**Comment by znarf** [comment]
@Betree ok, looking good to me.

**Pull request merged**
