### PR TITLE
Show Processing Contributions in Managed Contributions Section 

### PR DESCRIPTION
**Pull request by SudharakaP**
Related to, https://github.com/opencollective/opencollective/issues/6826

⚠️ Require: https://github.com/opencollective/opencollective-api/pull/9079

image

### CODE REVIEW

**Comment by lost-pixel-signals** [comment]
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 0  | ❗       |

**Comment by lost-pixel-signals** [comment]
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 0  | ❗       |

**Comment by lost-pixel-signals** [comment]
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 0  | ❗       |

**Comment by SudharakaP** [comment]
As per the new changes to the API side this is no longer needed.

**Pull request closed without merging**
