### PR TITLE
Optimization: only load admin collectives

### PR DESCRIPTION
**Pull request by znarf**
This should help load (and compute) less data in the loggedInUser query.

### CODE REVIEW

**Comment by znarf** [comment]
@Betree Interesting, forgot about `MEMBER`. Should we have `CONTRIBUTOR` to?

**Comment by Betree** [comment]
@znarf Ah yes good catch! `CONTRIBUTOR` is actually the role attributed when you submit expenses

**Comment by znarf** [comment]
We actually do

```
LoggedInUser.memberOf.filter(m => m.role !== 'BACKER'),
      m => m.collective.id,
    );
```

So we should actually get everything except `BACKER` ?

**Comment by Betree** [comment]
Yes, it actually make sense to show `HOST`(for host users for example). I'd say we don't need the `FOLLOWER` roles nether, but it's not used yet so we don't have to worry to much about it.

**Pull request closed without merging**
