### PR TITLE
update to TOS to accurately reflect current platform terminology

### PR DESCRIPTION
**Pull request by alanna**
Updated language in the TOS to accurately reflect how we use terminology on the platform. 

This includes:

* Backers and Sponsor → Financial Contributors
* Combining the seperate sections for Backers and Sponsors into one
* Members → Contributors
* Requestors → Expense Submitters
* Reimbursements → Payments (because invoices are not reimbursements)
* Organizer → Collective Administrator

Also fixed some formatting problems.

FYI - I considered this important to update because it's an aspect of transparency. Our documentation and app UI should match our terms so people can read it and clearly understand what we are referring to.

### CODE REVIEW

**Comment by alanna** [comment]
Arg just realised I failed to update the "last updated" date at the top of the page. Do I have to create a whole new pull request for that or can that change be sneaked in somehow?

**Comment by alanna** [comment]
Oh forgot to mention, I did not run build:langs because it appeared this page is not in the translation system (didn't see any other language.json files for it).

I also updated some broken URLs to the updated addresses.

**Comment by znarf** [comment]
@alanna you can

1. Go to https://github.com/opencollective/opencollective-frontend/blob/tos-update/static/tos.md
2. Edit
3. Commit directly to the branch

**Comment by znarf** [comment]
Should we email users to tell them the TOS were updated?

**Comment by alanna** [comment]
OK I committed the small change to update the date directly.

Regarding informing users of the change to TOS, I'm not sure. I have not changed any of the legal requirements or relationships in a material way. I only updated what the different roles are called and fixed some formatting issues and broken links.

@xdamman do you know of any guidelines about informing users of changes to TOS? If it's a small change that doesn't impact the legal agreements beyond phrasing, should we still inform them? Or is it enough to include an announcement in the newsletter or something like that?

**Pull request merged**
