### PR TITLE
fix Admin can see Updates section when Updates is disabled

### PR DESCRIPTION
**Pull request by jeffin143**
Resolve https://github.com/opencollective/opencollective/issues/3177

# Description

Resolve https://github.com/opencollective/opencollective/issues/3177
# Screenshots

### CODE REVIEW

**Comment by znarf** [comment]
@Betree Could you review this one? I'm personally unsure about what is the expected behavior.

**Comment by Betree** [comment]
@jeffin143 did you have time to look at this one already?

**Comment by jeffin143** [comment]
I ll take a look, sorry didn't see it was there

**Comment by Betree** [comment]
Closing as stale. @jeffin143 feel free to contribute again to this when you'll have more time

**Pull request closed without merging**
