### PR TITLE
feat: Implemented gift card filter from transactions page

### PR DESCRIPTION
**Pull request by vickywane**
This PR resolves [this](https://github.com/opencollective/opencollective/issues/3452) 

# Description
Although still a work in progress this PR adds an option to filter and return only Gift cards from the Transactions page as requested in [this](https://github.com/opencollective/opencollective/issues/3452) issue.

# Screenshots
Screenshot from 2021-02-01 13-27-25

### CODE REVIEW

**Comment by vickywane** [comment]
@Betree I am currently working on this feature. 
Currently, I have added done the UI parts within the frontend app but I would like to get some clarification before proceeding.

Can I just write a function to filter and show results containing only gift cards, Or do I re-fetch the data as it's done with the two other filters?

Can you please assist with a staging/test account having gift card transactions within a test collection?

**Comment by Betree** [comment]
> @Betree I am currently working on this feature.
> Currently, I have added done the UI parts within the frontend app but I would like to get some clarification before proceeding.
> 
> Can I just write a function to filter and show results containing only gift cards, Or do I re-fetch the data as it's done with the two other filters?
> 
> Can you please assist with a staging/test account having gift card transactions within a test collection?

Filtering must happen on the API side, so you do need to refetch the data.

https://staging.opencollective.com/triplebyte is usually a good candidate for testing gift cards, but since this needs some API work you will need to be able to set this up locally:
- Create an organization
- Go to settings > Gift Cards > Create gift cards
- Pick "I'll send the codes myself" in the form and submit
- Copy-paste one of the generated links to claim the gift card
- Make a contribution to any collective, just pick the gift card at the payment step

**Comment by vickywane** [comment]
I'm working on this.

**Comment by Betree** [comment]
@vickywane any news on this one?

**Comment by vickywane** [comment]
Sorry for the delay on this. I ran into some errors while using the db creation scripts within the opencollective-api in my debian environment. 

I would work on it again

**Comment by Betree** [comment]
Closing for now, feel free to re-open if you find more time to work on this

**Pull request closed without merging**
