### PR TITLE
add rel="me" attribute to collective links

### PR DESCRIPTION
**Pull request by MFTabriz**
This lets collectives to verify their links on 3rd party websites.

### CODE REVIEW

**Comment by MFTabriz** [comment]
isn't it possible to see the Vercel logs without creating an account there?

**Comment by znarf** [comment]
Here is the error:

Screenshot 2022-12-10 at 16 32 37

**Comment by MFTabriz** [comment]
@znarf if anything is not clear in this PR, I can clarify/improve it.

**Comment by znarf** [comment]
Sorry for the late review, there was a similar work that was tackled in https://github.com/opencollective/opencollective-frontend/pull/8456 and I was unsure if it was still relevant.

I've now rebased and fixed the conflicts.

**Comment by znarf** [comment]
Thank you for your contribution @MFTabriz !

**Pull request closed without merging**
