### PR TITLE
Pricing: improve contact button responsiveness

### PR DESCRIPTION
**Pull request by AARYAN-MAHENDRA**
Resolve https://github.com/opencollective/opencollective/issues/3225#issue-635633010

# Description
Modified components/pricing/PricingTable.js so that the contact button does not show any irregularities.

# Screenshots
on full-screen
on full size screen.

on med-size screen
on med sized and less screens.

### CODE REVIEW

**Comment by AARYAN-MAHENDRA** [comment]
Thanks for pointing out the error @Betree , I will make changes in the css as you  suggest.

**Comment by Betree** [comment]
@AARYAN-MAHENDRA any update on this one?

**Comment by AARYAN-MAHENDRA** [comment]
I am really sorry @betree I am a university student and am stuck with exams right now. I will do it by today itself.
Actually I tried to change the css but it getting cluttered and now looking good.So I suggest that will it be okay to cut the text (on mid size and less screens) as soon as the space is encountered.Its looking pretty neat and good.

**Comment by Betree** [comment]
> I am really sorry @Betree I am a university student and am stuck with exams right now. I will do it by today itself.

@AARYAN-MAHENDRA no problem, we try to avoid stuck PRs because they can create conflicts and can become tedious to manage, but we don't expect you to deliver with a deadline (thanks for contributing!).

> So I suggest that will it be okay to cut the text (on mid size and less screens) as soon as the space is encountered.Its looking pretty neat and good.

I explained in details in https://github.com/opencollective/opencollective-frontend/pull/4431#pullrequestreview-431451876 why cutting the text is not a solution, mainly internationalization. In some languages, saying just `Contact` (or `Us`, because you can't predict the words position) will not mean anything. Open Collective is currently translated in 13+ languages, so we can't go with this solution.

**Comment by Betree** [comment]
Another example: in Spanish, `Contact us` is translated by `Contáctanos`, which is a single word (without space). According to the translator, it's `お問い合わせ` in Japanese.

**Comment by AARYAN-MAHENDRA** [comment]
@Betree I changed the  css as you asked. But it seems like a check is failing I am still new on github so I don't know what's wrong. Hope you can help, and really sorry for the trouble I have caused you.

**Comment by AARYAN-MAHENDRA** [comment]
O my God what the Hell happened. I was just Updating my curent forked copy from my system.How did this come to pass.

**Comment by snitin315** [comment]
it seems your fork was too much outdated and hence too much changes in PR because of the merge commit.
you can always reset your branch with `git reset --hard upstream/master`

**Comment by AARYAN-MAHENDRA** [comment]
Thanks a lot, @snitin315 .It seemed like my heart was about to pop out. I mean I didn't know this would happen . Thanks anyway. 
I have created a new PR https://github.com/opencollective/opencollective-frontend/pull/4586#issue-444147643 regarding the same.
Actually, I have been inspired from you sir to do open source I have seen your video with Aman Dattharwal and am trying to walk on your footsteps. I am a first-year in my college and its an honour to be able to talk to you.

**Pull request closed without merging**
