### PR TITLE
feat: correct pricing status in host settings

### PR DESCRIPTION
**Pull request by jamesgeorge007**
Fixes https://github.com/opencollective/opencollective/issues/3193

# Description
- Rephrase information for hosts on free plan.

# Screenshots

### CODE REVIEW

**Comment by jamesgeorge007** [comment]
While testing out the `Receiving Money` page locally an error seems to pop up relating to the `GraphQL` field validations on the course of form submission:-
```sh
Error: GraphQL error: Validation error: Invalid format of BANK_ACCOUNT payout method data
```

I did provide the values for `account`, `amount`, `collective` and `reference` fields.
@znarf can you please give me a better picture regarding the intended approach.

**Comment by znarf** [comment]
@kewitz could you answer?

**Comment by kewitz** [comment]
Hey, I'm investigating that now.
@jamesgeorge007 can you confirm that you're testing the frontend using the staging API? (this is the default, you have no .env file in the root of your frontend folder)

**Comment by jamesgeorge007** [comment]
It seems to occur in both cases.

**Comment by jamesgeorge007** [comment]
Is there any documentation available on how  a collective admin is expected to update the respective information?

**Comment by jamesgeorge007** [comment]
\cc @kewitz

**Comment by kewitz** [comment]
Hi @jamesgeorge007, I don't think our documentation is explicit about these steps.
We're counting on the UX to make this explicit enough for now, but feel free to update the documentation.

For context, setting up a bank account instruction to receive money is only available for Hosts, collectives that are enabled as a fiscal host. You can enable your collective in _Settings -> Fiscal Host_:
image

Related to the bug, could you rebase your branch on top of master and try it again?
If that doesn't solve the issue, could you paste here request that is failing?

**Comment by kewitz** [comment]
Stale.

**Pull request closed without merging**
